function c(answer, clues) {
  return { answer, clues: clues.split(' ') };
}

function f(answer, columns) {
  return { answer, columns };
}

export const LEVELS = [
  {
    id: 'putovanje',
    title: 'Putovanje',
    icon: '✈️',
    colors: ['#2563eb', '#0891b2'],
    finals: [
      f('aerodrom', [
        c('gejt', 'ukrcavanje tabla broj red čekanje terminal'),
        c('pista', 'poletanje sletanje beton svjetla točkovi brzina'),
        c('pasoš', 'slika dokument pečat granica identitet državljanstvo'),
        c('prtljag', 'kofer traka etiketa težina čekiranje torba'),
        c('kontrola', 'skener policija torba metal sigurnost prolaz'),
        c('pilot', 'kabina kapetan uniforma komande let slušalice'),
      ]),
      f('hotel', [
        c('recepcija', 'pult prijava osoblje ključ gost dolazak'),
        c('soba', 'krevet ormar kupatilo prozor noćenje mir'),
        c('kartica', 'vrata čip ključ ulaz plastika brava'),
        c('lift', 'sprat dugme kabina hodnik vrata uspon'),
        c('doručak', 'jutro kafa pecivo sok tanjir švedski'),
        c('minibar', 'frižider piće čokolada soba račun flašica'),
      ]),
      f('plaža', [
        c('pijesak', 'zrno stopala obala kula lopatica vruć'),
        c('suncobran', 'hlad platno štap krug zaštita sunce'),
        c('peškir', 'mokro sušenje tkanina ležanje torba kupanje'),
        c('krema', 'faktor koža sunce zaštita miris mazanje'),
        c('talasi', 'pjena obala voda šum plivanje more'),
        c('ležaljka', 'odmor naslon plastika peškir sunčanje red'),
      ]),
      f('voz', [
        c('stanica', 'tabla polazak dolazak čekanje klupa peron'),
        c('peron', 'broj šine kofer putnici najava ivica'),
        c('pruga', 'šina prag kamen metal pravac tunel'),
        c('vagon', 'sjedište prozor vrata kupe hodnik broj'),
        c('kondukter', 'uniforma karta pregled kliješta putnik kontrola'),
        c('lokomotiva', 'vuča mašina početak motor dim snaga'),
      ]),
      f('kamp', [
        c('šator', 'platno klin konopac ulaz podloga noć'),
        c('vreća', 'spavanje zatvarač toplota rolanje podloga jutro'),
        c('vatra', 'drva plamen žar dim krug toplota'),
        c('lampa', 'baterija svjetlo mrak noć šator prekidač'),
        c('ranac', 'leđa kaiš džep oprema voda težina'),
        c('termos', 'čaj toplo poklopac metal izlet gutljaj'),
      ]),
      f('kofer', [
        c('točkići', 'vučenje pod aerodrom hodnik plastika okretanje'),
        c('ručka', 'ruka izvlačenje držanje plastika metal vučenje'),
        c('brava', 'šifra ključ zatvaranje sigurnost klik metal'),
        c('etiketa', 'ime adresa papir vezivanje prepoznavanje prtljag'),
        c('odjeća', 'majica čarape pantalone jakna slaganje ormar'),
        c('pregrada', 'ziper džep mrežica prostor odvajanje unutra'),
      ]),
      f('luka', [
        c('sidro', 'lanac dno metal spuštanje stajanje brod'),
        c('dok', 'beton obala vez brod ukrcaj pristanište'),
        c('kran', 'teret dizanje kontejner kuka visina luka'),
        c('mornar', 'posada uniforma konopac paluba rad brod'),
        c('trajekt', 'auto paluba prelaz putnici karta more'),
        c('svjetionik', 'svjetlo obala noć signal brod toranj'),
      ]),
      f('granica', [
        c('rampa', 'prelaz vozila dizanje kontrola kolona metal'),
        c('carina', 'roba pregled službenik torba prijava granica'),
        c('pasoš', 'slika dokument pečat identitet država putnik'),
        c('viza', 'dozvola ambasada boravak papir ulazak pečat'),
        c('kolona', 'vozila čekanje putnici red prelaz strpljenje'),
        c('pečat', 'tinta datum ulaz izlaz pasoš službenik'),
      ]),
      f('plan puta', [
        c('ruta', 'linija cilj skretanje kilometri mapa pravac'),
        c('rezervacija', 'datum potvrda smeštaj mejl cijena dolazak'),
        c('budžet', 'novac trošak račun štednja cijena plan'),
        c('raspored', 'vreme dan polazak obilazak satnica lista'),
        c('mapa', 'ulice oznake legenda lokacija pravac papir'),
        c('spisak', 'stvari pakovanje provjera telefon bilješka priprema'),
      ]),
      f('suvenirnica', [
        c('magnet', 'frižider grad uspomena mali poklon slika'),
        c('razglednica', 'slika pošta marka poruka putovanje papir'),
        c('figura', 'polica ukras mali grad spomenik predmet'),
        c('majica', 'natpis veličina pamuk grad poklon odjeća'),
        c('prodavac', 'kasa račun osmijeh kupac cijena radnja'),
        c('kesa', 'kupovina ručka logo plastika poklon nošenje'),
      ]),
    ],
  },
  {
    id: 'skola',
    title: 'Škola',
    icon: '🎓',
    colors: ['#1d4ed8', '#7c3aed'],
    finals: [
      f('učionica', [
        c('tabla', 'kreda marker brisanje formula zadatak zid'),
        c('klupa', 'sjedenje učenik torba knjiga red drvo'),
        c('profesor', 'predavanje pitanje ocjena dnevnik autoritet glas'),
        c('zvono', 'odmor početak kraj hodnik zvuk čas'),
        c('sunđer', 'brisanje prašina voda kreda ruka tabla'),
        c('dnevnik', 'imena ocjene razred evidencija profesor papir'),
      ]),
      f('ispit', [
        c('pitanja', 'papir odgovor zadatak bodovi test znanje'),
        c('olovka', 'grafit pisanje gumica vrh ruka papir'),
        c('vreme', 'sat minuta rok kraj pritisak tišina'),
        c('nervoza', 'strah znoj čekanje misli trema rezultat'),
        c('ocjena', 'broj bodovi uspjeh dnevnik rezultat profesor'),
        c('prepisivanje', 'puškica pogled rizik kazna tajno klupa'),
      ]),
      f('knjiga', [
        c('korice', 'naslov autor slika tvrdo zaštita boja'),
        c('stranice', 'papir broj list tekst čitanje okretanje'),
        c('poglavlje', 'naslov dio redosled nastavak sadržaj kraj'),
        c('autor', 'pisac ime priča ideja tekst potpis'),
        c('marker', 'oznaka mjesto čitanje trakica stranica nastavak'),
        c('biblioteka', 'police tišina pozajmica kartica čitaonica knjige'),
      ]),
      f('domaći', [
        c('sveska', 'linije korice papir beleške predmet pisanje'),
        c('zadatak', 'vežba rešenje rok profesor lekcija problem'),
        c('rok', 'datum predaja vreme kašnjenje obaveza pritisak'),
        c('lekcija', 'tema knjiga učenje ponavljanje znanje predmet'),
        c('greška', 'ispravka gumica crveno provjera tačno pogrešno'),
        c('roditelj', 'pomoć provjera kuća dijete strpljenje savjet'),
      ]),
      f('fakultet', [
        c('student', 'indeks ispit skripta predavanje semestar učenje'),
        c('amfiteatar', 'sjedišta sala profesor mikrofon tabla redovi'),
        c('kolokvijum', 'test bodovi dio gradivo termin semestar'),
        c('skripta', 'kopija lekcije papir podvlačenje ispit stranice'),
        c('mentor', 'savjet tema rad konsultacije profesor sastanak'),
        c('diploma', 'potpis zvanje svečanost završetak papir odbrana'),
      ]),
      f('matematika', [
        c('jednačina', 'x nepoznata jednakost rešenje znak račun'),
        c('formula', 'pravilo pamćenje zadatak tabla postupak znak'),
        c('geometrija', 'krug trougao ugao lenjir površina oblik'),
        c('kalkulator', 'dugmad ekran rezultat baterija račun funkcija'),
        c('razlomak', 'brojilac imenilac crta polovina dio račun'),
        c('grafik', 'osa kriva tačka koordinata funkcija mreža'),
      ]),
      f('biblioteka', [
        c('polica', 'knjige red oznaka prašina visina drvo'),
        c('čitaonica', 'sto lampa tišina student koncentracija knjiga'),
        c('članarina', 'kartica ime broj uplata rok biblioteka'),
        c('katalog', 'naslov autor pretraga polica broj sistem'),
        c('bibliotekar', 'pult pomoć knjiga pozajmica tišina rad'),
        c('pozajmica', 'rok vraćanje knjiga kartica evidencija čitalac'),
      ]),
      f('raspored', [
        c('čas', 'predmet profesor vreme učionica zvono trajanje'),
        c('nedelja', 'ponedeljak petak dani vikend plan nastava'),
        c('smjena', 'jutro popodne nastava dolazak odlazak škola'),
        c('odmor', 'pauza hodnik užina zvono razgovor kratko'),
        c('tabla', 'obavještenje promjena papir učionica dan raspored'),
        c('predmet', 'matematika jezik istorija knjiga profesor čas'),
      ]),
      f('laboratorija', [
        c('epruveta', 'staklo tečnost stalak hemija uzorak usko'),
        c('mikroskop', 'sočivo uzorak uvećanje stolčić biologija oko'),
        c('mantil', 'bijelo zaštita rukav laboratorija profesor tkanina'),
        c('rukavice', 'guma ruke zaštita hemikalija jednokratno par'),
        c('reagens', 'tečnost kap reakcija boja boca hemija'),
        c('plamenik', 'vatra gas toplota epruveta eksperiment sto'),
      ]),
      f('školska torba', [
        c('ranac', 'leđa kaiš džep knjige patent škola'),
        c('pernica', 'olovke gumica bojice lenjir ziper torba'),
        c('sveska', 'linije korice papir beleške predmet pisanje'),
        c('užina', 'sendvič sok kutija odmor hljeb jabuka'),
        c('udžbenik', 'lekcija korice predmet stranice škola znanje'),
        c('patent', 'otvaranje zatvaranje zubi metal džep torba'),
      ]),
    ],
  },
  {
    id: 'dom',
    title: 'Dom',
    icon: '🏠',
    colors: ['#be123c', '#c2410c'],
    finals: [
      f('kuća', [
        c('vrata', 'kvaka ključ ulaz prag brava hodnik'),
        c('prozor', 'staklo roletna zavjesa pogled okvir svjetlo'),
        c('krov', 'crijep dimnjak tavan kiša zaštita visina'),
        c('dvorište', 'trava ograda kapija bašta sto napolje'),
        c('fasada', 'zid boja malter spolja prozor kuća'),
        c('dimnjak', 'dim krov cigla peć grijanje otvor'),
      ]),
      f('stan', [
        c('zgrada', 'sprat ulaz lift fasada komšije stanari'),
        c('balkon', 'ograda saksija pogled stolica vazduh sprat'),
        c('interfon', 'zvono glas ulaz dugme gost vrata'),
        c('lift', 'dugme kabina sprat vrata čekanje uspon'),
        c('računi', 'struja voda grijanje mjesec plaćanje papir'),
        c('komšija', 'zid buka pozdrav vrata pomoć hodnik'),
      ]),
      f('kuhinja', [
        c('šporet', 'ringla plin lonac toplota ručak dugme'),
        c('frižider', 'hladno vrata polica mlijeko hrana led'),
        c('sudopera', 'slavina voda suđe pranje sapun odvod'),
        c('daska', 'sječenje nož povrće drvo priprema površina'),
        c('aspirator', 'para miris filter ventilator dim kuvanje'),
        c('kanta', 'otpad kesa poklopac miris čišćenje ugao'),
      ]),
      f('kupatilo', [
        c('tuš', 'voda kabina para sapun slavina kupanje'),
        c('lavabo', 'slavina zubi sapun odvod ogledalo voda'),
        c('ogledalo', 'odraz lice staklo brijanje jutro lavabo'),
        c('pločice', 'zid pod sjaj fugne voda hladno'),
        c('četkica', 'zubi pasta jutro veče higijena čaša'),
        c('peškir', 'sušenje tkanina mokro polica mekan kupanje'),
      ]),
      f('spavaća soba', [
        c('krevet', 'san jastuk ćebe dušek noć odmor'),
        c('ormar', 'odjeća vješalica polica vrata fioka slaganje'),
        c('budilnik', 'alarm jutro vreme zvuk buđenje sto'),
        c('noćni sto', 'lampa knjiga telefon čaša sat strana'),
        c('posteljina', 'čaršaf navlaka jastuk pranje krevet bijelo'),
        c('zavjesa', 'prozor mrak tkanina privatnost jutro svjetlo'),
      ]),
      f('porodica', [
        c('roditelji', 'briga savjet pomoć sigurnost razgovor dom'),
        c('djeca', 'igra smijeh igračke škola soba trčanje'),
        c('ručak', 'sto tanjiri okupljanje razgovor nedjelja jelo'),
        c('fotografija', 'album okvir uspomena osmijeh zid slika'),
        c('praznik', 'gosti poklon slavlje jelo ukras kuća'),
        c('uspomena', 'priča detinjstvo album vreme zajedno putovanje'),
      ]),
      f('dnevna soba', [
        c('kauč', 'sjedenje jastuk odmor mekan televizor porodica'),
        c('televizor', 'ekran daljinski film kanal zvuk slika'),
        c('tepih', 'pod šara mekan usisavanje prašina boja'),
        c('stolić', 'daljinski čaša knjiga sredina drvo dnevna'),
        c('lampa', 'svjetlo ugao sijalica veče čitanje prekidač'),
        c('polica', 'ukrasi knjige fotografija zid red prašina'),
      ]),
      f('garaža', [
        c('auto', 'parking vrata beton guma ulje hauba'),
        c('alat', 'čekić šrafciger kliješta popravka metal polica'),
        c('bicikl', 'točkovi lanac pedala zid kaciga vožnja'),
        c('vrata', 'daljinski šine otvaranje rampa garaža auto'),
        c('kutije', 'karton stvari skladište oznaka prašina selidba'),
        c('beton', 'pod sivo hladno mrlja tvrdo garaža'),
      ]),
      f('vešeraj', [
        c('mašina', 'bubanj pranje program voda deterdžent veš'),
        c('deterdžent', 'prah miris mjera pranje kutija sapunica'),
        c('korpa', 'odjeća prljavo nošenje plastika kupatilo veš'),
        c('sušilica', 'toplota bubanj peškir odjeća program sušenje'),
        c('štipaljka', 'konopac odjeća vjetar plastika kačenje pritisak'),
        c('pegla', 'para toplota košulja daska ravnanje kabl'),
      ]),
      f('hodnik', [
        c('ulaz', 'vrata prag kvaka ključ stan kuća'),
        c('čiviluk', 'jakna kaput vješanje kuka zid hodnik'),
        c('cipele', 'pertle đon par ulaz blato obuća'),
        c('ogledalo', 'odraz izlazak lice staklo zid pogled'),
        c('tepih', 'otirač prašina stopala ulaz pod hodnik'),
        c('svjetlo', 'prekidač plafon sijalica mrak ulaz lampa'),
      ]),
    ],
  },
  {
    id: 'priroda',
    title: 'Priroda',
    icon: '🌿',
    colors: ['#15803d', '#65a30d'],
    finals: [
      f('šuma', [
        c('stablo', 'kora grana krošnja korijen deblo drvo'),
        c('lišće', 'zeleno jesen šuštanje krošnja opadanje grana'),
        c('mahovina', 'kamen vlaga zeleno hlad mekano sjena'),
        c('staza', 'trag hodanje zemlja markacija šetnja usko'),
        c('pečurka', 'šešir kiša zemlja vlaga rast otrov'),
        c('potok', 'voda kamen žubor tok obala hladno'),
      ]),
      f('rijeka', [
        c('izvor', 'početak voda planina hladno čisto tok'),
        c('korito', 'dno kamen voda pravac obala dubina'),
        c('obala', 'trava pijesak ribar šetnja kamen voda'),
        c('most', 'prelaz ograda luk beton iznad put'),
        c('ušće', 'spajanje more kraj širina voda tok'),
        c('brzak', 'pjena kamen brzina buka opasnost tok'),
      ]),
      f('planina', [
        c('vrh', 'visina pogled cilj uspon snijeg stijena'),
        c('staza', 'markacija kamen uspon hodanje trag putokaz'),
        c('ranac', 'voda hrana oprema leđa kaiš težina'),
        c('dom', 'planinar čaj sklonište krevet odmor drvo'),
        c('stijena', 'kamen litica tvrdo penjanje sivo visina'),
        c('magla', 'bijelo vidljivost hladno jutro oblak vrh'),
      ]),
      f('more', [
        c('talasi', 'pjena obala vjetar šum plivanje dubina'),
        c('horizont', 'linija daljina nebo sunce plavo pogled'),
        c('so', 'ukus kristal voda koža bijelo more'),
        c('školjka', 'pijesak obala oblik suvenir zvuk spiralno'),
        c('brod', 'paluba sidro kapetan luka plovidba more'),
        c('galeb', 'krila obala riba let zvuk nebo'),
      ]),
      f('kiša', [
        c('oblak', 'sivo nebo kap voda nevrijeme sjena'),
        c('kap', 'prozor voda pad mokro mala zvuk'),
        c('kišobran', 'platno ručka zaštita otvaranje mokro ulica'),
        c('lokva', 'asfalt voda odraz cipela prskanje rupa'),
        c('grmljavina', 'zvuk munja oluja nebo strah noć'),
        c('duga', 'boje luk poslije sunce nebo kiša'),
      ]),
      f('snijeg', [
        c('pahulja', 'bijela oblik hladno nebo lagano zima'),
        c('led', 'klizav hladan tvrd voda staklo zima'),
        c('sanke', 'spust djeca drvo brzina brdo zima'),
        c('trag', 'stopa otisak cipela bijelo put snijeg'),
        c('grudva', 'ruka bacanje bijelo igra okruglo hladno'),
        c('lopata', 'čišćenje prilaz snijeg metal ručka zima'),
      ]),
      f('jezero', [
        c('obala', 'trska kamen trava voda šetnja mirno'),
        c('čamac', 'veslo drvo ribar plovidba voda mir'),
        c('odraz', 'slika voda nebo drvo površina mirno'),
        c('patka', 'kljun perje plivanje jato obala voda'),
        c('trska', 'visoko zeleno obala voda vjetar ptica'),
        c('ribolov', 'štap udica mamac čekanje obala riba'),
      ]),
      f('cvijet', [
        c('latica', 'boja miris nježno krug proljeće cvijet'),
        c('stabljika', 'zeleno uspravno list voda rast tanko'),
        c('polen', 'žuto prah alergija pčela proljeće cvijet'),
        c('pčela', 'nektar krila zujanje med cvijet ubod'),
        c('vaza', 'staklo voda sto buket ukras kuća'),
        c('miris', 'nos parfem proljeće svježe latica cvijet'),
      ]),
      f('oluja', [
        c('munja', 'svjetlo nebo bljesak struja oblak noć'),
        c('grmljavina', 'zvuk tutnjava strah nebo poslije munja'),
        c('vjetar', 'udar krošnje prozor hladno pravac snaga'),
        c('pljusak', 'jaka kiša voda ulica kap mokro'),
        c('oblak', 'tamno sivo nebo nevrijeme sjena oluja'),
        c('nestanak', 'struja mrak svijeća kuća kvar prekid'),
      ]),
      f('livada', [
        c('trava', 'zeleno košenje zemlja visoko miris stopala'),
        c('cvijeće', 'boje latice pčele proljeće buket polje'),
        c('leptir', 'krila boje let cvijet lagano insekt'),
        c('rosa', 'kap jutro trava svjetlucanje hladno voda'),
        c('sijeno', 'suvo trava miris bala ljeto kosidba'),
        c('puteljak', 'zemlja usko hodanje trag kroz livada'),
      ]),
    ],
  },
  {
    id: 'zivotinje',
    title: 'Životinje',
    icon: '🐾',
    colors: ['#92400e', '#ca8a04'],
    finals: [
      f('pas', [
        c('povodac', 'šetnja ruka ogrlica kontrola ulica kaiš'),
        c('njuška', 'nos miris vlažno trag hrana disanje'),
        c('lajanje', 'zvuk glas dvorište oprez noć komšija'),
        c('šapa', 'trag kandža jastučić hod korak mekano'),
        c('kost', 'žvakanje zubi bijelo igra hrana glodanje'),
        c('kućica', 'dvorište krov drvo spavanje zaklon lanac'),
      ]),
      f('mačka', [
        c('brkovi', 'lice tanko nos osjetilo dodir mačka'),
        c('mjaukanje', 'zvuk glad pažnja noć glas mače'),
        c('kandže', 'oštre šapa grebanje lov namještaj penjanje'),
        c('krzno', 'dlaka meko linjanje četka toplo boja'),
        c('klupko', 'vuna igra kotrljanje šapa konac mače'),
        c('pijesak', 'kutija posip lopatica miris čišćenje kuća'),
      ]),
      f('konj', [
        c('kopito', 'potkovica noga trag tvrdo zvuk zemlja'),
        c('sedlo', 'koža jahanje leđa uzde oprema sjedenje'),
        c('uzde', 'ruke kontrola pravac koža jahač sedlo'),
        c('griva', 'dlaka vrat vjetar četka duga ljepota'),
        c('štala', 'slama vrata hrana sijeno miris farma'),
        c('galop', 'brzina polje trk ritam snaga kopita'),
      ]),
      f('ptica', [
        c('krilo', 'let perje mahanje nebo visina zamah'),
        c('gnijezdo', 'grane jaja mladunci drvo sigurnost proljeće'),
        c('kljun', 'sjeme hrana oštro zvuk žuto hranjenje'),
        c('pero', 'lagano mekano boja krilo rep let'),
        c('jato', 'grupa nebo pravac selidba let ptice'),
        c('pjesma', 'jutro grana melodija zvuk proljeće cvrkut'),
      ]),
      f('riba', [
        c('peraja', 'plivanje ravnoteža voda pokret tijelo rep'),
        c('škrge', 'disanje voda otvor tijelo život kiseonik'),
        c('krljušt', 'sjaj srebrno zaštita tijelo koža voda'),
        c('udica', 'mamac štap ribolov čekanje voda ribar'),
        c('akvarijum', 'staklo voda biljke hrana kuća filter'),
        c('mreža', 'hvatanje konopac čamac ribar more izvlačenje'),
      ]),
      f('pčela', [
        c('košnica', 'med vosak matica roj saće okvir'),
        c('saće', 'ćelije vosak šestougao med žuto košnica'),
        c('ubod', 'žaoka bol otok oprez koža odbrana'),
        c('nektar', 'cvijet slatko skupljanje proljeće latica hrana'),
        c('krila', 'zujanje let prozirno brzo malo insekt'),
        c('matica', 'kraljica jaja roj košnica glavna pčele'),
      ]),
      f('lav', [
        c('griva', 'dlaka vrat mužjak zlatno kralj snaga'),
        c('rika', 'zvuk savana glas opasnost moć strah'),
        c('savana', 'trava afrika sunce prostor lov vrućina'),
        c('čopor', 'lavice mladunci grupa lov porodica vođa'),
        c('plijen', 'lov trčanje hrana životinja napad savana'),
        c('kandže', 'oštre šapa napad lov snaga plijen'),
      ]),
      f('slon', [
        c('surla', 'nos duga voda hvatanje hrana prskanje'),
        c('kljova', 'bijelo zub duga slonovača par odbrana'),
        c('uho', 'veliko mahanje toplota glava sivo slon'),
        c('krdo', 'grupa mladunci porodica zaštita savana kretanje'),
        c('težina', 'veliko stopalo zemlja hod snaga trag'),
        c('blato', 'kupanje hlađenje voda koža prskanje savana'),
      ]),
      f('zmija', [
        c('ljuske', 'koža šara tijelo zaštita presvlačenje hladno'),
        c('otrov', 'ugriz opasnost zubi bol lijek strah'),
        c('jezik', 'račvast miris usta pokret oprez zmija'),
        c('puzanje', 'tlo vijuganje tiho trava tijelo kretanje'),
        c('terarijum', 'staklo grana pijesak voda zatvoreno kuća'),
        c('zviždanje', 'zvuk oprez usta napad strah tiho'),
      ]),
      f('žirafa', [
        c('vrat', 'dug visina list drvo glava žirafa'),
        c('šare', 'mrlje smeđe koža tijelo prepoznavanje boja'),
        c('jezik', 'dug tamno list hvatanje hrana usta'),
        c('kopito', 'noga hod trag tvrdo zemlja visina'),
        c('akacija', 'drvo list trnje savana hrana visoko'),
        c('mladunče', 'malo majka rast zaštita krdo visoko'),
      ]),
    ],
  },
  {
    id: 'umetnost',
    title: 'Umjetnost',
    icon: '🎨',
    colors: ['#db2777', '#9333ea'],
    finals: [
      f('slika', [
        c('platno', 'ram površina boja atelje zategnuto slikar'),
        c('četkica', 'vlakna potez boja ruka voda drška'),
        c('paleta', 'miješanje nijansa boje drvo krug slikar'),
        c('boja', 'tuba pigment sloj nijansa sušenje potez'),
        c('ram', 'ivica zid drvo zaštita galerija okvir'),
        c('motiv', 'portret pejzaž prizor ideja detalj kompozicija'),
      ]),
      f('muzika', [
        c('nota', 'linije znak melodija papir ritam kompozitor'),
        c('ritam', 'tempo takt bubanj ponavljanje ples otkucaj'),
        c('gitara', 'žice akord trzalica drvo solo vrat'),
        c('klavir', 'tipke crno bijelo pedala prsti melodija'),
        c('mikrofon', 'glas kabl pjevač bina zvuk koncert'),
        c('refren', 'pjesma ponavljanje tekst melodija publika pjevanje'),
      ]),
      f('pozorište', [
        c('scena', 'daske zavjesa svjetlo kulisa gluma publika'),
        c('glumac', 'uloga tekst kostim pokret glas replika'),
        c('zavjesa', 'crveno otvaranje kraj početak tkanina scena'),
        c('publika', 'sjedišta aplauz tišina reakcija sala gledanje'),
        c('režiser', 'upute proba vizija tekst ekipa scena'),
        c('karta', 'red sjedište blagajna cijena datum ulaz'),
      ]),
      f('film', [
        c('kamera', 'objektiv snimanje kadar režiser stativ scena'),
        c('scenario', 'tekst dijalog radnja scena autor papir'),
        c('glumac', 'uloga kostim dijalog lik scena premijera'),
        c('montaža', 'rez kadar ritam rezanje zvuk slika'),
        c('bioskop', 'platno mrak kokice sjedište karta zvuk'),
        c('plakat', 'naslov glumci najava zid reklama slika'),
      ]),
      f('muzej', [
        c('eksponat', 'predmet vitrina opis istorija zbirka pažnja'),
        c('vitrina', 'staklo zaštita zaključano predmet svjetlo opis'),
        c('kustos', 'postavka vodič stručnjak znanje posao muzej'),
        c('ulaznica', 'karta šalter cijena datum posjeta papir'),
        c('zbirka', 'predmeti čuvanje vrijednost istorija postavka muzej'),
        c('posjetioci', 'grupa tišina hodnik pogled pitanja razgledanje'),
      ]),
      f('ples', [
        c('korak', 'stopalo pokret takt vežba ritam ples'),
        c('partner', 'par držanje okret ruka sklad scena'),
        c('koreografija', 'redosled pokret plan grupa tačnost vežba'),
        c('kostim', 'haljina sjaj boja nastup scena pokret'),
        c('muzika', 'tempo ritam melodija zvuk sala pjesma'),
        c('aplauz', 'publika kraj dlanovi uspjeh osmijeh zvuk'),
      ]),
      f('skulptura', [
        c('kamen', 'mermer tvrdo dlijeto prašina oblik figura'),
        c('bronza', 'metal sjaj liv spomenik kip boja'),
        c('dlijeto', 'alat udarac kamen ruka oblik rezanje'),
        c('postament', 'baza visina natpis oslonac muzej kamen'),
        c('kipar', 'umjetnik materijal atelje figura rad oblik'),
        c('figura', 'tijelo poza lice forma detalj umjetnost'),
      ]),
      f('strip', [
        c('kadar', 'okvir scena crtež redosled stranica slika'),
        c('oblačić', 'tekst govor misao balon lik dijalog'),
        c('junak', 'kostim avantura hrabrost moć priča protivnik'),
        c('onomatopeja', 'zvuk slova udarac efekat prasak akcija'),
        c('tabla', 'stranica kadrovi papir niz naslov čitanje'),
        c('scenarista', 'priča dijalog tekst radnja autor ideja'),
      ]),
      f('fotografija', [
        c('objektiv', 'staklo fokus zum aparat svjetlo krug'),
        c('blic', 'svjetlo mrak bljesak trenutak dugme aparat'),
        c('kadar', 'okvir scena kompozicija izbor pogled slika'),
        c('portret', 'lice osoba poza pogled svjetlo pozadina'),
        c('album', 'slike uspomena stranice porodica papir red'),
        c('fokus', 'oštrina detalj zamućenje objektiv lice kadar'),
      ]),
      f('izložba', [
        c('galerija', 'zid slike prostor tišina publika svjetlo'),
        c('katalog', 'opis autor radovi papir lista postavka'),
        c('otvaranje', 'gosti govor vino veče umjetnik događaj'),
        c('kustos', 'postavka izbor radova objašnjenje muzej stručnjak'),
        c('natpis', 'naziv autor godina pored djelo pločica'),
        c('posjetioci', 'razgledanje pitanja tišina hodnik pogled grupa'),
      ]),
    ],
  },
  {
    id: 'prevoz',
    title: 'Prevoz',
    icon: '🚗',
    colors: ['#0f766e', '#2563eb'],
    finals: [
      f('automobil', [
        c('volan', 'ruke skretanje pravac vozač kontrola krug'),
        c('motor', 'hauba gorivo ulje snaga zvuk brzina'),
        c('guma', 'točak felna šara asfalt pritisak rezerva'),
        c('retrovizor', 'ogledalo nazad pogled ugao staklo sigurnost'),
        c('pojas', 'kopča sigurnost rame sjedište klik putnik'),
        c('semafor', 'crveno žuto zeleno raskrsnica stop signal'),
      ]),
      f('autobus', [
        c('stanica', 'klupa tabla linija čekanje red putnici'),
        c('vozač', 'volan ruta uniforma kabina kočenje ogledalo'),
        c('karta', 'cijena papir validacija kontrolor zona vožnja'),
        c('rukohvat', 'stajanje gužva metal držanje ravnoteža putnici'),
        c('vrata', 'otvaranje zatvaranje stepenik dugme ulaz izlaz'),
        c('linija', 'broj ruta stanice mapa grad raspored'),
      ]),
      f('tramvaj', [
        c('šina', 'ulica metal kolosjek točak pravac stanica'),
        c('stanica', 'tabla linija čekanje putnici peron grad'),
        c('pantograf', 'struja krov kabl mreža iskra napajanje'),
        c('zvono', 'signal upozorenje zvuk vozač gužva skretanje'),
        c('karta', 'validacija aparat cijena kontrola papir vožnja'),
        c('vozač', 'kabina komande ogledalo kočenje uniforma pravac'),
      ]),
      f('avion', [
        c('krilo', 'let vazduh motor oblaci visina stabilnost'),
        c('pilot', 'kabina kapetan komande uniforma slušalice let'),
        c('pista', 'poletanje sletanje beton svjetla aerodrom brzina'),
        c('sjedište', 'pojas prozor red naslon putnik broj'),
        c('stjuardesa', 'uniforma piće sigurnost osmijeh prolaz upute'),
        c('turbina', 'motor buka krilo okretanje snaga vazduh'),
      ]),
      f('bicikl', [
        c('pedala', 'noga okretanje lanac pogon ritam vožnja'),
        c('lanac', 'metal zupčanik mast pogon pedala okvir'),
        c('točak', 'guma felna krug osovina okretanje put'),
        c('kočnica', 'ručica zaustavljanje pakne sigurnost brzina kontrola'),
        c('volan', 'ruke skretanje ručke pravac kontrola upravljanje'),
        c('kaciga', 'glava zaštita traka pad sigurnost vozač'),
      ]),
      f('brod', [
        c('sidro', 'lanac dno luka stajanje metal spuštanje'),
        c('paluba', 'ograda šetnja mornari gore kapetan more'),
        c('kapetan', 'komanda kormilo posada kurs uniforma brod'),
        c('kormilo', 'pravac okretanje kontrola drvo kapetan more'),
        c('mornar', 'posada konopac uniforma paluba luka rad'),
        c('kabina', 'krevet prozor vrata putnik mala brod'),
      ]),
      f('taksi', [
        c('taksimetar', 'cijena kilometri ekran vožnja iznos vreme'),
        c('adresa', 'ulica broj odredište navigacija grad cilj'),
        c('vozač', 'volan ruta razgovor licenca auto sjedište'),
        c('gepek', 'kofer prtljag vrata prostor torba putnik'),
        c('poziv', 'telefon aplikacija narudžba čekanje lokacija broj'),
        c('račun', 'plaćanje kartica gotovina kraj papir iznos'),
      ]),
      f('metro', [
        c('tunel', 'podzemlje mrak šina zid brzina svjetlo'),
        c('stanica', 'peron mapa linija izlaz gužva tabla'),
        c('eskalator', 'stepenice pokret gore dolje ljudi stanica'),
        c('vagon', 'vrata putnici sjedišta rukohvat prozor voz'),
        c('karta', 'automat zona validacija cijena ulaz papir'),
        c('mapa', 'linije boje stanice čvor pravac grad'),
      ]),
      f('kamion', [
        c('teret', 'roba kutije težina paleta isporuka skladište'),
        c('prikolica', 'dužina točkovi spoj metal transport teret'),
        c('kabina', 'sjedište volan radio krevet prozor vozač'),
        c('dizel', 'gorivo pumpa rezervoar cijena potrošnja motor'),
        c('utovar', 'viljuškar rampa roba paleta radnik skladište'),
        c('isporuka', 'adresa paket rok potpis kupac kamion'),
      ]),
      f('semafor', [
        c('crveno', 'stop čekanje signal zabrana raskrsnica svjetlo'),
        c('žuto', 'oprez promjena signal kratko svjetlo raskrsnica'),
        c('zeleno', 'kreni prolaz dozvola signal vozač pješak'),
        c('raskrsnica', 'ulice skretanje pješaci automobili pravac centar'),
        c('stub', 'metal visina kabl kutija ulica semafor'),
        c('pješak', 'prelaz dugme zebra čekanje signal ulica'),
      ]),
    ],
  },
  {
    id: 'sport',
    title: 'Sport',
    icon: '⚽',
    colors: ['#16a34a', '#0f766e'],
    finals: [
      f('fudbal', [
        c('gol', 'mreža stativa šut rezultat lopta slavlje'),
        c('teren', 'trava linije centar korner aut stadion'),
        c('sudija', 'pištaljka karton faul pravila odluka teren'),
        c('kopačke', 'đon pertle trava udarac oprema brzina'),
        c('navijači', 'tribina pjesma zastava aplauz buka klub'),
        c('kapiten', 'traka tim vođa dres izbor igrači'),
      ]),
      f('košarka', [
        c('koš', 'obruč mrežica tabla poeni šut skok'),
        c('dribling', 'lopta pod ruka kontrola brzina prodor'),
        c('trojka', 'linija daljina šut pogodak publika poeni'),
        c('parket', 'sala pod patike odskok linije teren'),
        c('faul', 'kontakt sudija pištaljka kazna slobodna linija'),
        c('tajm aut', 'trener pauza klupa savjet taktika minuta'),
      ]),
      f('tenis', [
        c('reket', 'žice drška loptica udarac servis oprema'),
        c('servis', 'bacanje početak as linija brzina reket'),
        c('mreža', 'sredina teren prepreka loptica visina poen'),
        c('šljaka', 'crveno prašina trag klizanje teren patike'),
        c('gem', 'poeni set meč prednost rezultat tabla'),
        c('sudija', 'stolica odluka aut linija poen meč'),
      ]),
      f('plivanje', [
        c('bazen', 'voda staza hlor pločice dubina skok'),
        c('naočare', 'oči guma providno zaštita voda lice'),
        c('kapica', 'glava kosa guma boja takmičenje voda'),
        c('kraul', 'ruke disanje stil zamah brzina voda'),
        c('start', 'blok pištaljka skok reakcija trka početak'),
        c('medalja', 'postolje zlato pobjeda rezultat takmičenje plivač'),
      ]),
      f('skijanje', [
        c('skije', 'duge klizanje rubovi vosak spust oprema'),
        c('pancerice', 'čizma kopča tvrdo stopalo skija oprema'),
        c('žičara', 'sjedište uspon planina red karta visina'),
        c('štapovi', 'ruke oslonac par metal ravnoteža snijeg'),
        c('staza', 'spust oznaka krivina brzina planina snijeg'),
        c('kaciga', 'glava zaštita pad naočare sigurnost brzina'),
      ]),
      f('teretana', [
        c('tegovi', 'kilogrami metal ruke snaga serija podizanje'),
        c('traka', 'trčanje ekran brzina korak kardio znoj'),
        c('klupa', 'ležanje tegovi prsa oslonac sprava sala'),
        c('ogledalo', 'odraz forma zid tijelo vežba pogled'),
        c('trener', 'plan tehnika savjet motivacija cilj forma'),
        c('svlačionica', 'ormarić tuš peškir patike torba odmor'),
      ]),
      f('odbojka', [
        c('mreža', 'visina teren sredina preko blok lopta'),
        c('servis', 'početak udarac linija lopta as rotacija'),
        c('smeč', 'skok snaga napad poen ruka blok'),
        c('blok', 'ruke mreža odbrana skok napad zaustavljanje'),
        c('prijem', 'podlaktica servis kontrola odbrana lopta tim'),
        c('libero', 'dres odbrana prijem specijalista parket brzina'),
      ]),
      f('boks', [
        c('rukavice', 'šake koža udarac zaštita ring crveno'),
        c('ring', 'konopci ugao pod sudija publika borba'),
        c('runda', 'gong vreme pauza minuta sudija borba'),
        c('nokaut', 'pad odbrojavanje pobjeda udarac sudija publika'),
        c('gard', 'ruke lice zaštita stav odbrana borac'),
        c('trener', 'ugao savjeti peškir taktika glas priprema'),
      ]),
      f('rukomet', [
        c('golman', 'odbrana mreža skok šut ruke dres'),
        c('sedmerac', 'linija penal šut golman sudija pogodak'),
        c('lopta', 'ljepljivo ruka dodavanje šut igra okruglo'),
        c('krilo', 'strana brzina skok ugao napad igrač'),
        c('pivot', 'linija prostor blok leđa napad igrač'),
        c('isključenje', 'dvije minute kazna klupa sudija faul'),
      ]),
      f('atletika', [
        c('staza', 'tartan linije krug trka cilj start'),
        c('štoperica', 'sekunde vreme rezultat trener mjerenje start'),
        c('koplje', 'bacanje zalet oštro daljina ruka teren'),
        c('prepona', 'skok barijera staza ritam noga trka'),
        c('cilj', 'traka kraj vreme pobjeda rezultat aplauz'),
        c('broj', 'majica učesnik takmičenje papir identitet trka'),
      ]),
    ],
  },
  {
    id: 'tehnologija',
    title: 'Tehnologija',
    icon: '💻',
    colors: ['#7c3aed', '#4f46e5'],
    finals: [
      f('kompjuter', [
        c('monitor', 'ekran piksel rezolucija svjetlo sto slika'),
        c('tastatura', 'slova tipke unos pisanje prečica kabl'),
        c('miš', 'klik kursor točkić podloga dugme ruka'),
        c('procesor', 'čip jezgro brzina računanje toplota hardver'),
        c('memorija', 'ram modul podaci kapacitet brzina program'),
        c('disk', 'fajl folder prostor čuvanje podaci kopija'),
      ]),
      f('telefon', [
        c('ekran', 'dodir staklo aplikacija osvjetljenje prst zaštita'),
        c('baterija', 'punjenje procenat kabl trajanje ikona struja'),
        c('kamera', 'autoportret sočivo slika blic fokus video'),
        c('kartica', 'broj operater mreža signal poziv telefon'),
        c('punjač', 'kabl adapter utičnica baterija struja brzina'),
        c('obavještenje', 'zvuk poruka traka vibracija ekran telefon'),
      ]),
      f('internet', [
        c('ruter', 'bežično signal lampica kabl lozinka mreža'),
        c('browser', 'tab adresa stranica pretraga prozor veza'),
        c('veza', 'adresa klik plavo povezivanje dijeljenje stranica'),
        c('server', 'podaci zahtjev odgovor mreža računar pristup'),
        c('email', 'adresa poruka prilog sanduče slanje pošta'),
        c('download', 'fajl brzina traka folder internet završetak'),
      ]),
      f('aplikacija', [
        c('ikonica', 'slika telefon meni prečica ekran klik'),
        c('dugme', 'dodir akcija pritisak tekst boja ekran'),
        c('profil', 'ime slika nalog korisnik avatar podešavanja'),
        c('login', 'email lozinka ulazak sesija nalog sigurnost'),
        c('meni', 'opcije lista izbor navigacija ekran dugme'),
        c('update', 'verzija promjena instalacija prodavnica download napredak'),
      ]),
      f('programiranje', [
        c('kod', 'linije sintaksa editor fajl logika funkcija'),
        c('funkcija', 'ime poziv parametar povratak kod rezultat'),
        c('bug', 'greška crash problem test popravka poruka'),
        c('git', 'commit branch repo push pull verzija'),
        c('terminal', 'komanda putanja tekst izlaz proces ekran'),
        c('debug', 'breakpoint konzola trag vrijednost greška test'),
      ]),
      f('lozinka', [
        c('šifra', 'slova brojevi znakovi tajna unos polje'),
        c('nalog', 'korisnik email profil prijava aplikacija pristup'),
        c('dvokorak', 'kod telefon potvrda poruka sigurnost prijava'),
        c('reset', 'email link promjena zaborav nalog potvrda'),
        c('token', 'kod pristup vreme server potvrda aplikacija'),
        c('haker', 'napad krađa podaci rizik mreža oprez'),
      ]),
      f('kamera', [
        c('sočivo', 'staklo fokus zum objektiv svjetlo oštrina'),
        c('blic', 'svjetlo mrak bljesak trenutak dugme slika'),
        c('memorija', 'kartica fajl prostor snimak čuvanje kapacitet'),
        c('stativ', 'noge stabilno visina snimanje ugao kamera'),
        c('kadar', 'okvir scena kompozicija izbor pogled fotografija'),
        c('video', 'snimak pokret zvuk kadar film kamera'),
      ]),
      f('printer', [
        c('papir', 'list ladica bijelo dokument izlaz stranica'),
        c('toner', 'prah crno kaseta štampa boja zamjena'),
        c('kertridž', 'mastilo boja zamjena štampa glava plastika'),
        c('skeniranje', 'staklo dokument kopija slika poklopac uređaj'),
        c('kopija', 'duplikat papir dokument broj stranica dugme'),
        c('zaglavljivanje', 'papir greška vađenje ladica zastoj štampa'),
      ]),
      f('robot', [
        c('senzor', 'detekcija pokret svjetlo ulaz mjerenje signal'),
        c('motor', 'okretanje osovina struja brzina snaga točak'),
        c('ruka', 'zglob hvatanje prsti servo alat pokret'),
        c('baterija', 'napajanje punjenje energija trajanje ćelija kabl'),
        c('program', 'naredba kod kontrola algoritam izvršenje logika'),
        c('metal', 'tijelo šraf ram ploča konstrukcija čvrsto'),
      ]),
      f('cloud', [
        c('upload', 'slanje fajl server internet traka folder'),
        c('backup', 'kopija sigurnost povratak čuvanje podaci server'),
        c('sinhronizacija', 'uređaji update kopija veza automatski vreme'),
        c('prostor', 'gigabajt kapacitet limit nalog plaćanje fajl'),
        c('dijeljenje', 'link dozvola pristup folder tim email'),
        c('server', 'podaci centar mreža odgovor zahtjev računar'),
      ]),
    ],
  },
  {
    id: 'hrana',
    title: 'Hrana',
    icon: '🍕',
    colors: ['#f97316', '#dc2626'],
    finals: [
      f('ručak', [
        c('tanjir', 'porcija keramika sto pribor ivica jelo'),
        c('supa', 'kašika lonac para bujon povrće toplo'),
        c('meso', 'tiganj roštilj pečenje nož porcija protein'),
        c('salata', 'krastavac paradajz ulje činija svježe zeleno'),
        c('hljeb', 'kriška korica brašno pekara pecivo miris'),
        c('pribor', 'viljuška nož kašika salveta metal sto'),
      ]),
      f('pizza', [
        c('tijesto', 'brašno kvasac voda miješenje kora rerna'),
        c('sir', 'topljenje kačkavalj žuto rendanje mlijeko ukus'),
        c('paradajz', 'sos crveno pelat kriška povrće kiselkasto'),
        c('origano', 'začin trava miris teglica italija zeleno'),
        c('šunka', 'meso kriška topping slano ružičasto pečenje'),
        c('kutija', 'karton dostava poklopac porudžbina vruće kuća'),
      ]),
      f('kafa', [
        c('zrno', 'mljevenje prženje mlin aroma braon arabika'),
        c('šolja', 'drška keramika gutljaj tanjirić toplo napitak'),
        c('mlijeko', 'pjena kapućino bijelo čaša dodatak krava'),
        c('šećer', 'kocka kristal slatko kašičica tegla bijelo'),
        c('aparat', 'dugme para kapsula voda espresso kuhinja'),
        c('kafić', 'konobar sto račun terasa društvo šolja'),
      ]),
      f('hljeb', [
        c('brašno', 'pšenica bijelo prah kesa mlin tijesto'),
        c('kvasac', 'dizanje fermentacija mehurići toplota tijesto miris'),
        c('korica', 'hrskavo braon ivica pečenje miris kora'),
        c('sredina', 'mekano bijelo kriška toplo rupice hljeb'),
        c('pekara', 'pecivo red jutro prodavnica toplo miris'),
        c('mrvica', 'sto pod sitno čišćenje kriška korica'),
      ]),
      f('čokolada', [
        c('kakao', 'zrno braon gorko prah biljka ukus'),
        c('tabla', 'kockica red lomljenje folija omot komad'),
        c('šećer', 'slatko kristal bijelo kocka tegla dodatak'),
        c('mlijeko', 'bijelo kremasto krava napitak dodatak čaša'),
        c('lješnik', 'orašasto tvrdo punjenje krckanje ukus kolač'),
        c('omot', 'papir marka folija boja otvaranje reklama'),
      ]),
      f('restoran', [
        c('meni', 'jelo cijena izbor stranica ponuda konobar'),
        c('konobar', 'uniforma tacna narudžba gost račun sto'),
        c('račun', 'cijena plaćanje kusur papir novac kraj'),
        c('rezervacija', 'sto datum ime telefon dolazak mjesto'),
        c('kuvar', 'kuhinja recept začin lonac vruće jelo'),
        c('gosti', 'večera razgovor stolice društvo atmosfera narudžba'),
      ]),
      f('sladoled', [
        c('kornet', 'vafl hrskavo drška kugla jestivo ljeto'),
        c('kugla', 'okruglo kašika porcija ukus kornet slatko'),
        c('vanila', 'bijelo miris krema ukus štapić slatko'),
        c('čokolada', 'braon kakao preliv komadić ukus slatko'),
        c('jagoda', 'crveno voće sirup svježe ukus ljeto'),
        c('zamrzivač', 'hladno led fioka čuvanje vrata kuhinja'),
      ]),
      f('supa', [
        c('lonac', 'poklopac para kuvanje voda metal ringla'),
        c('kašika', 'metal duboko gutljaj tanjir jelo pribor'),
        c('bujon', 'tečnost ukus kocka slano toplo supa'),
        c('rezanci', 'tanko tijesto žuto kašika mekano supa'),
        c('šargarepa', 'narandžasto korijen povrće sjeckanje zdravo supa'),
        c('peršun', 'zeleno list miris začin tanjir svježe'),
      ]),
      f('sendvič', [
        c('hljeb', 'kriška korica mekano brašno doručak pecivo'),
        c('sir', 'žuto kriška mlijeko topljenje slano sendvič'),
        c('šunka', 'meso kriška ružičasto slano dodatak sendvič'),
        c('salata', 'list zeleno hrskavo svježe povrće dodatak'),
        c('namaz', 'mazanje nož krem tegla maslac hljeb'),
        c('papir', 'umotavanje užina torba škola zaštita sendvič'),
      ]),
      f('palačinke', [
        c('tijesto', 'brašno mlijeko jaja smjesa miješanje tečno'),
        c('tiganj', 'ravno toplota pečenje okretanje ringla ulje'),
        c('namaz', 'krem džem čokolada mazanje slatko tegla'),
        c('rolanje', 'uvijanje tanjir punjenje krug savijanje palačinka'),
        c('šećer', 'prah posipanje bijelo slatko kašika dekoracija'),
        c('sirup', 'preliv slatko flaša ljepljivo ukus palačinke'),
      ]),
    ],
  },
];

export const LETTERS = ['A', 'B', 'C', 'D'];
