function c(answer, clues) {
  return { answer, clues: clues.split(' ') };
}

function f(answer, columns) {
  return { answer, columns };
}

export const LEVELS = [
  {
    id: 'putovanje',
    title: 'Putovanje',
    icon: '✈',
    colors: ['#2563eb', '#0891b2'],
    finals: [
      f('odmor', [
        c('hotel', 'soba recepcija ključ noćenje doručak gost'),
        c('plaža', 'pijesak talasi suncobran peškir ležaljka krema'),
        c('kofer', 'odjeća točkići brava pakovanje prtljag ručka'),
        c('rezervacija', 'datum potvrda email cijena dolazak odlazak'),
        c('more', 'so obala dubina plavo brod horizont'),
        c('avion', 'krila pilot let kabina pista gejt'),
        c('suvenir', 'magnet poklon uspomena prodavnica razglednica figura'),
        c('kupaći', 'voda plaža ljeto peškir sunce torba'),
      ]),
      f('aerodrom', [
        c('gejt', 'ukrcavanje tabla broj red čekanje putnici'),
        c('avion', 'krila pilot pista let kabina sjedište'),
        c('prtljag', 'kofer traka težina etiketa torba kontrola'),
        c('pasoš', 'dokument slika pečat granica identitet država'),
        c('kontrola', 'skener red torba policija sigurnost prolaz'),
        c('karta', 'sjedište let cijena rezervacija telefon papir'),
        c('pilot', 'uniforma kabina komande let kapetan mikrofon'),
        c('pista', 'svjetla poletanje sletanje točkovi brzina beton'),
      ]),
      f('hotel', [
        c('recepcija', 'pult prijava ključ osoblje gost čekanje'),
        c('soba', 'krevet ormar prozor kupatilo ključ mir'),
        c('lift', 'sprat dugme kabina hodnik vrata uspon'),
        c('doručak', 'jutro kafa pecivo sto sok tanjir'),
        c('rezervacija', 'datum ime potvrda email cijena dolazak'),
        c('apartman', 'soba kuhinja terasa krevet gost ključ'),
        c('peškir', 'kupatilo tuš bijelo mekano sušenje polica'),
        c('usluga', 'osoblje čišćenje soba telefon zahtjev gost'),
      ]),
      f('voz', [
        c('stanica', 'peron tabla čekanje polazak putnici klupa'),
        c('vagon', 'sjedišta prozor vrata kupe hodnik broj'),
        c('pruga', 'šine metal pravac kamen tunel most'),
        c('kondukter', 'uniforma karta pregled putnik vagon torba'),
        c('lokomotiva', 'mašina vuča snaga početak dim voz'),
        c('karta', 'cijena sjedište kontrola polazak papir datum'),
        c('peron', 'stanica čekanje broj tabla gužva kofer'),
        c('kupe', 'prozor sjedište vrata prtljag putnik mir'),
      ]),
      f('more', [
        c('talasi', 'pjena obala vjetar zvuk dubina plivanje'),
        c('brod', 'paluba sidro kapetan luka plovidba kabina'),
        c('plaža', 'pijesak suncobran peškir ležaljka krema sunce'),
        c('galeb', 'krila obala let riba nebo zvuk'),
        c('ostrvo', 'kopno voda palme izolacija obala mapa'),
        c('ronjenje', 'maska peraja dubina riba disanje oprema'),
        c('luka', 'brod vez sidro mornar obala kapetan'),
        c('horizont', 'daljina sunce linija nebo plavo pogled'),
      ]),
      f('mapa', [
        c('kompas', 'sjever igla pravac jug orijentacija krug'),
        c('ruta', 'plan cilj skretanje kilometri put linija'),
        c('grad', 'ulica trg zgrada naselje mapa adresa'),
        c('granica', 'država prelaz carina linija pasoš znak'),
        c('oznaka', 'simbol boja legenda mjesto pravac znak'),
        c('put', 'asfalt raskrsnica znak pravac kilometri vozilo'),
        c('gps', 'telefon signal lokacija navigacija strelica ekran'),
        c('skretanje', 'lijevo desno raskrsnica pravac znak vožnja'),
      ]),
      f('kofer', [
        c('odjeća', 'majica pantalone jakna čarape ormar slaganje'),
        c('brava', 'ključ šifra sigurnost zatvaranje metal kofer'),
        c('točkići', 'vučenje hodnik aerodrom kretanje pod ručka'),
        c('pakovanje', 'spisak slaganje prostor put torba priprema'),
        c('prtljag', 'traka težina etiketa torba avion kontrola'),
        c('ručka', 'ruka vučenje plastika kofer držanje put'),
        c('etiketa', 'ime adresa papir traka kofer prepoznavanje'),
        c('torba', 'rame džep kaiš stvar odjeća put'),
      ]),
      f('kamp', [
        c('šator', 'platno klin vreća noć priroda ulaz'),
        c('vatra', 'drva plamen toplota dim krug veče'),
        c('ranac', 'oprema leđa džep težina kaiš voda'),
        c('priroda', 'šuma trava rijeka tišina vazduh ptice'),
        c('vreća', 'spavanje toplota zatvarač noć šator podloga'),
        c('lampa', 'baterija svjetlo mrak šator noć kamp'),
        c('izlet', 'društvo hrana staza planina odmor dan'),
        c('roštilj', 'žar meso miris rešetka dim dvorište'),
      ]),
      f('granica', [
        c('pasoš', 'slika dokument pečat država identitet kontrola'),
        c('carina', 'pregled roba kontrola službenik torba granica'),
        c('prelaz', 'rampa kolona tabla čekanje vozilo dokument'),
        c('viza', 'dozvola ambasada boravak papir putovanje pečat'),
        c('država', 'zastava mapa jezik grad granica zakon'),
        c('kontrola', 'policija dokument pregled pitanje rampa red'),
        c('kolona', 'vozila čekanje putnici granica vrućina strpljenje'),
        c('pečat', 'pasoš tinta datum ulaz izlaz službenik'),
      ]),
      f('izlet', [
        c('piknik', 'ćebe korpa hrana trava društvo sunce'),
        c('planina', 'vrh staza pogled uspon priroda vazduh'),
        c('autobus', 'vozač stanica sjedište grupa karta polazak'),
        c('društvo', 'prijatelji smijeh razgovor slika grupa dan'),
        c('ranac', 'sendvič voda oprema leđa džep staza'),
        c('fotoaparat', 'slika objektiv uspomena klik baterija kadar'),
        c('vodič', 'tura priča znanje grupa putnici pravac'),
        c('odmor', 'pauza klupa hlad sendvič pogled mir'),
      ]),
    ],
  },
  {
    id: 'skola',
    title: 'Škola',
    icon: '🎓',
    colors: ['#1d4ed8', '#7c3aed'],
    finals: [
      f('učionica', [c('klupe', 'red sjedenje učenici drvo torba knjiga'), c('tabla', 'kreda marker zadatak brisanje pisanje formula'), c('profesor', 'predavanje pitanje ocjena znanje dnevnik autoritet'), c('zvono', 'odmor početak kraj hodnik zvuk škola'), c('prozor', 'svjetlo pogled vazduh staklo učionica zavjesa'), c('dnevnik', 'ocjene imena papir profesor čas evidencija'), c('spužva', 'brisanje tabla prašina voda kreda ruka'), c('predmet', 'matematika istorija jezik čas knjiga raspored')]),
      f('profesor', [c('predavanje', 'glas tabla tema znanje studenti objašnjenje'), c('ocjena', 'broj uspjeh test dnevnik rezultat škola'), c('pitanje', 'odgovor ruka znanje čas diskusija provjera'), c('katedra', 'sto profesor knjige papir učionica mjesto'), c('ispit', 'test znanje pitanja vrijeme rezultat nervoza'), c('dnevnik', 'ocjene imena razred evidencija papir profesor'), c('kreda', 'tabla bijelo prašina pisanje ruka učionica'), c('autoritet', 'poštovanje pravila znanje glas učionica red')]),
      f('knjiga', [c('stranice', 'papir broj tekst list čitanje poglavlje'), c('korice', 'naslov slika autor zaštita boja papir'), c('lekcija', 'tema učenje znanje zadatak predmet škola'), c('biblioteka', 'police tišina knjige čitaonica pozajmica članarina'), c('autor', 'pisac ime tekst ideja knjiga naslov'), c('poglavlje', 'dio naslov redosled radnja stranice nastavak'), c('sadržaj', 'lista stranice teme početak pregled naslov'), c('bilješka', 'olovka margina tekst podsjetnik učenje znak')]),
      f('ispit', [c('pitanja', 'papir znanje odgovor test profesor bodovi'), c('vrijeme', 'sat rok minuta kraj pritisak kontrola'), c('ocjena', 'rezultat broj uspjeh dnevnik bodovi profesor'), c('nervoza', 'strah čekanje znoj tišina test misli'), c('olovka', 'pisanje grafit gumica papir odgovor ruka'), c('klupa', 'sjedenje papir učionica student torba drvo'), c('prepisivanje', 'rizik pogled papir kazna tajno profesor'), c('rezultat', 'bodovi ocjena uspjeh čekanje papir objava')]),
      f('fakultet', [c('student', 'indeks predavanje ispit skripta učenje grupa'), c('indeks', 'ocjena potpis predmet student papir fakultet'), c('predavanje', 'amfiteatar profesor tema bilješke slajd čas'), c('amfiteatar', 'sjedišta velika sala profesor studenti tabla'), c('skripta', 'kopija lekcija papir učenje ispit stranice'), c('kolokvijum', 'test dio gradivo bodovi termin student'), c('mentor', 'savjet rad tema profesor pomoć sastanak'), c('diploma', 'završetak papir potpis uspjeh svečanost zvanje')]),
      f('domaći', [c('zadatak', 'vježba sveska rok kuća profesor rješenje'), c('sveska', 'linije papir bilješke korice predmet pisanje'), c('olovka', 'grafit pisanje gumica šiljalo ruka vrh'), c('rok', 'vrijeme predaja datum obaveza pritisak zadatak'), c('lekcija', 'učenje knjiga tema znanje škola ponavljanje'), c('roditelj', 'pomoć kuća provjera dijete zadatak strpljenje'), c('internet', 'pretraga pomoć primjer računar odgovor stranica'), c('greška', 'ispravka gumica crveno provjera zadatak učenje')]),
      f('raspored', [c('časovi', 'predmeti dan vrijeme škola redosled zvono'), c('sedmica', 'ponedjeljak petak dani plan nastava vikend'), c('predmet', 'knjiga profesor učionica tema ocjena čas'), c('pauza', 'odmor hodnik užina zvono razgovor kratko'), c('tabla', 'obavještenje papir promjena učionica raspored dan'), c('smjena', 'jutro popodne nastava dolazak odlazak škola'), c('učionica', 'broj sprat klupe tabla predmet čas'), c('zvono', 'početak kraj odmor hodnik zvuk vrijeme')]),
      f('biblioteka', [c('police', 'knjige red prašina tišina visina drvo'), c('čitaonica', 'sto tišina lampa student knjiga koncentracija'), c('pozajmica', 'članarina rok knjiga kartica vraćanje bibliotekar'), c('katalog', 'pretraga naslov autor broj polica sistem'), c('bibliotekar', 'pomoć knjiga tišina pult članarina rad'), c('tišina', 'šapat koncentracija znak čitanje prostor mir'), c('knjige', 'naslovi korice stranice znanje police čitanje'), c('kartica', 'član ime broj pozajmica plastika evidencija')]),
      f('matematika', [c('brojevi', 'račun cifra zadatak rezultat zbir razlika'), c('tabla', 'formula kreda profesor rješenje primjer pisanje'), c('geometrija', 'krug trougao lenjir ugao površina oblik'), c('jednačina', 'x nepoznata rješenje znak jednakost račun'), c('kalkulator', 'dugmad ekran rezultat račun baterija pomoć'), c('zadatak', 'tekst rješenje postupak greška provjera vježba'), c('lenjir', 'mjerenje linija centimetar geometrija škola plastika'), c('formula', 'pravilo znak pamćenje zadatak tabla rješenje')]),
      f('diploma', [c('papir', 'potpis pečat ime datum svečanost okvir'), c('svečanost', 'odijelo govor aplauz porodica sala osmijeh'), c('uspjeh', 'trud ocjene kraj rad ponos cilj'), c('zvanje', 'fakultet profesija titula rad znanje diploma'), c('mentor', 'savjet rad komisija profesor odbrana tema'), c('odbrana', 'prezentacija komisija pitanja rad student trema'), c('fotografija', 'uspomena porodica osmijeh događaj album slika'), c('kapa', 'toga svečanost bacanje student završetak crno')]),
    ],
  },
  {
    id: 'dom',
    title: 'Dom',
    icon: '🏠',
    colors: ['#be123c', '#c2410c'],
    finals: [
      f('kuća', [c('vrata', 'kvaka ključ ulaz brava prag hodnik'), c('prozor', 'staklo zavjesa pogled svjetlo okvir roletna'), c('krov', 'crijep dimnjak kiša zaštita visina kuća'), c('dvorište', 'trava ograda kapija sto komšija bašta'), c('kuhinja', 'šporet frižider sudopera ručak miris lonac'), c('dnevna', 'kauč televizor sto porodica tepih lampa'), c('kupatilo', 'tuš peškir ogledalo pločice voda sapun'), c('spavaća', 'krevet jastuk ćebe san ormar noć')]),
      f('stan', [c('zgrada', 'sprat lift ulaz komšije hodnik fasada'), c('balkon', 'ograda pogled saksija stolica vazduh sprat'), c('komšija', 'vrata zvono razgovor zid buka pomoć'), c('lift', 'dugme kabina sprat vrata zgrada čekanje'), c('hodnik', 'svjetlo vrata tepih ulaz stan tišina'), c('računi', 'struja voda grijanje papir mjesec plaćanje'), c('interfon', 'zvono glas ulaz dugme vrata gost'), c('parking', 'auto mjesto garaža rampa zgrada stanar')]),
      f('soba', [c('krevet', 'jastuk ćebe san dušek posteljina noć'), c('ormar', 'odjeća polica vrata vješalica fioka slaganje'), c('sto', 'lampa knjiga računar stolica rad papir'), c('tepih', 'pod mekano šara usisavanje prašina boja'), c('prozor', 'pogled svjetlo zavjesa staklo vazduh okvir'), c('polica', 'knjige ukras zid red prašina drvo'), c('slika', 'zid ram uspomena boja ukras pogled'), c('lampa', 'svjetlo prekidač sto sijalica veče čitanje')]),
      f('kuhinja', [c('šporet', 'ringla toplota lonac ručak dugme plin'), c('frižider', 'hladno vrata polica mlijeko led hrana'), c('sudopera', 'voda slavina suđe pranje sapun odvod'), c('sto', 'stolice tanjir porodica doručak stolnjak razgovor'), c('ormar', 'šolje tanjiri police vrata kuhinja čaše'), c('lonac', 'poklopac para supa metal kuvanje ringla'), c('daska', 'sječenje nož povrće drvo priprema površina'), c('kanta', 'otpad kesa poklopac kuhinja čišćenje miris')]),
      f('kupatilo', [c('tuš', 'voda para kabina sapun peškir slavina'), c('ogledalo', 'odraz lice staklo lavabo jutro brijanje'), c('peškir', 'sušenje mekano bijelo polica kupanje tkanina'), c('lavabo', 'voda slavina zubi sapun ogledalo odvod'), c('pločice', 'zid pod sjaj voda čišćenje hladno'), c('kada', 'voda kupanje pjena odmor bijelo duboko'), c('četkica', 'zubi pasta jutro veče higijena čaša'), c('sapun', 'miris pjena ruke pranje čisto kupatilo')]),
      f('dnevna soba', [c('kauč', 'sjedenje jastuk odmor televizor porodica mekano'), c('televizor', 'ekran daljinski film zvuk kanal slika'), c('sto', 'daljinski čaša knjiga sredina dnevna drvo'), c('tepih', 'pod šara mekano usisivač prašina boja'), c('lampa', 'svjetlo veče ugao sijalica čitanje prekidač'), c('zavjesa', 'prozor tkanina svjetlo privatnost boja pomjeranje'), c('polica', 'ukrasi knjige zid fotografija red prašina'), c('gosti', 'razgovor kafa sjedenje posjeta smijeh porodica')]),
      f('dvorište', [c('trava', 'zeleno košenje zemlja lopta jutro miris'), c('ograda', 'drvo metal granica kapija komšija zaštita'), c('kapija', 'ulaz ključ šarke dvorište ulica otvaranje'), c('bašta', 'cvijeće zemlja sadnja voda povrće sunce'), c('roštilj', 'žar meso dim društvo sto miris'), c('sto', 'stolice napolje kafa ručak hlad porodica'), c('ljuljaška', 'dijete konopac drvo igra pokret smijeh'), c('komšija', 'pozdrav ograda razgovor pomoć ulica kuća')]),
      f('spavaća soba', [c('krevet', 'san jastuk ćebe dušek noć odmor'), c('ormar', 'odjeća vješalica polica vrata ogledalo fioka'), c('noćni sto', 'lampa knjiga telefon čaša sat strana'), c('zavjesa', 'prozor mrak privatnost tkanina jutro svjetlo'), c('jastuk', 'mekano glava san navlaka krevet odmor'), c('ćebe', 'toplo zima krevet tkanina san pokrivanje'), c('budilnik', 'alarm jutro vrijeme zvuk sto buđenje'), c('papuče', 'pod noge jutro udobno krevet kuća')]),
      f('garaža', [c('auto', 'parking vrata beton alat ulje guma'), c('alat', 'čekić šrafciger polica popravka metal ruka'), c('vrata', 'daljinski rampa otvaranje garaža auto šine'), c('bicikl', 'točkovi lanac pedala zid oprema vožnja'), c('polica', 'kutije alat prašina red zid prostor'), c('ulje', 'motor fleka miris kanta servis auto'), c('kutije', 'stvari selidba karton skladište oznaka prašina'), c('beton', 'pod hladno sivo garaža tvrdo mrlja')]),
      f('porodica', [c('sto', 'ručak razgovor tanjiri stolice dom okupljanje'), c('slika', 'uspomena zid album osmijeh okvir porodica'), c('dnevna', 'kauč televizor smijeh odmor veče zajedno'), c('kuhinja', 'miris ručak pomoć majka recept toplota'), c('praznik', 'gosti poklon jelo slavlje ukras porodica'), c('djeca', 'igra smijeh soba igračke škola trčanje'), c('roditelji', 'briga savjet dom pomoć razgovor sigurnost'), c('uspomena', 'fotografija priča putovanje djetinjstvo album vrijeme')]),
    ],
  },
  {
    id: 'priroda',
    title: 'Priroda',
    icon: '🌿',
    colors: ['#15803d', '#65a30d'],
    finals: [
      f('šuma', [c('drvo', 'stablo grana list korijen kora hlad'), c('lišće', 'zeleno jesen šuštanje grana zemlja krošnja'), c('staza', 'hodanje zemlja trag planina put šetnja'), c('mahovina', 'zeleno kamen vlaga hlad šuma mekano'), c('ptice', 'pjesma krila gnijezdo grana jutro let'), c('hlad', 'krošnja sunce odmor svježina drvo mir'), c('pečurka', 'kiša zemlja šešir šuma vlaga rast'), c('potok', 'voda kamen tok šum obala svježe')]),
      f('rijeka', [c('tok', 'voda pravac brzina korito obala izvor'), c('obala', 'kamen trava pijesak voda šetnja ribar'), c('most', 'prelaz luk beton rijeka ograda put'), c('izvor', 'početak voda planina čisto hladno tok'), c('ušće', 'kraj rijeka more voda spajanje širina'), c('ribar', 'štap udica mamac obala čekanje riba'), c('brzak', 'pjena kamen brzina voda zvuk opasnost'), c('čamac', 'veslo voda obala plovidba drvo mir')]),
      f('planina', [c('vrh', 'visina pogled uspon cilj snijeg stijena'), c('staza', 'hodanje markacija kamen šuma uspon trag'), c('stijena', 'kamen tvrdo sivo penjanje litica oblik'), c('snijeg', 'bijelo hladno zima vrh pahulja led'), c('dom', 'planinar odmor čaj krevet sklonište drvo'), c('pogled', 'daljina nebo dolina vrh ljepota mir'), c('ranac', 'oprema voda hrana leđa težina izlet'), c('vazduh', 'svježina hladno disanje visina priroda čisto')]),
      f('more', [c('talasi', 'pjena obala vjetar zvuk plivanje dubina'), c('obala', 'pijesak kamen šetnja voda plaža linija'), c('so', 'ukus voda more bijelo kristal koža'), c('riba', 'peraja voda mreža ribar jato plivanje'), c('horizont', 'daljina nebo linija sunce plavo pogled'), c('plaža', 'pijesak suncobran peškir sunce odmor obala'), c('školjka', 'oblik pijesak more suvenir obala zvuk'), c('brod', 'paluba luka kapetan plovidba sidro talasi')]),
      f('jezero', [c('voda', 'mirno površina plavo dubina odraz hladno'), c('čamac', 'veslo ribar drvo obala mir plovidba'), c('riba', 'udica mamac mreža voda plivanje ribar'), c('trska', 'obala zeleno visoko ptica voda vjetar'), c('odraz', 'slika voda nebo drvo mirno površina'), c('patka', 'perje voda plivanje kljun obala jato'), c('kamp', 'šator vatra obala noć priroda odmor'), c('magla', 'jutro voda hladno bijelo tišina obala')]),
      f('vjetar', [c('lišće', 'šuštanje grana jesen drvo pokret zvuk'), c('zastava', 'tkanina jarbol boje mahanje pravac vjetar'), c('oluja', 'kiša grmljavina oblaci snaga mrak strah'), c('propuh', 'vrata prozor hladno soba vazduh strujanje'), c('talasi', 'more pjena obala brod kretanje zvuk'), c('oblaci', 'nebo pokret sjena kiša sivo visina'), c('zmaj', 'papir konac nebo dijete igra let'), c('jedro', 'brod platno more pravac snaga plovidba')]),
      f('kiša', [c('oblak', 'sivo nebo kap voda sjena nevrijeme'), c('kap', 'voda prozor zvuk mokro mala pad'), c('kišobran', 'ručica platno zaštita ulica mokro otvaranje'), c('lokva', 'voda asfalt odraz cipela prskanje ulica'), c('grmljavina', 'zvuk munja oluja nebo strah noć'), c('kaput', 'mokro zaštita jesen odjeća ulica hladno'), c('miris', 'zemlja svježe trava poslije voda vazduh'), c('prozor', 'staklo kap soba pogled zvuk kiša')]),
      f('sunce', [c('svjetlost', 'dan zrak prozor toplota sjena nebo'), c('toplota', 'ljeto koža vrućina odmor zrak energija'), c('sjena', 'hlad drvo oblik sunce zaklon pod'), c('izlazak', 'jutro horizont boje dan početak nebo'), c('zalazak', 'veče crveno more horizont kraj pogled'), c('zrak', 'linija svjetlo prašina prozor sunce toplota'), c('naočare', 'staklo zaštita oči ljeto moda sunce'), c('krema', 'koža zaštita plaža ljeto faktor miris')]),
      f('snijeg', [c('pahulja', 'bijelo hladno oblik nebo zima lagano'), c('led', 'klizavo hladno voda staklo zima tvrdo'), c('sanke', 'spust djeca zima brzina drvo snijeg'), c('kaput', 'toplo zima odjeća hladno rukavi vuna'), c('trag', 'stopa snijeg put životinja cipela otisak'), c('skije', 'staza planina oprema spust brzina snijeg'), c('otapanje', 'voda sunce proljeće kap toplota kraj'), c('bijelo', 'boja zima pokrivač pahulje mir tišina')]),
      f('cvijet', [c('latica', 'boja miris nježno krug cvijet proljeće'), c('stabljika', 'zeleno uspravno list voda rast tanko'), c('pčela', 'med polen krila cvijet zujanje ubod'), c('buket', 'poklon vaza boje slavlje miris papir'), c('polen', 'žuto prah alergija pčela cvijet proljeće'), c('vaza', 'staklo voda sto buket ukras kuća'), c('bašta', 'zemlja sadnja zalivanje trava sunce rad'), c('miris', 'nos proljeće latica parfem nježno svježe')]),
    ],
  },
  {
    id: 'zivotinje',
    title: 'Životinje',
    icon: '🐾',
    colors: ['#7c2d12', '#b45309'],
    finals: [
      f('pas', [c('šapa', 'trag kandža hod mekano jastučić korak'), c('rep', 'mahanje radost ravnoteža pokret dug pas'), c('lajanje', 'zvuk dvorište oprez glas noć komšija'), c('ogrlica', 'vrat povodac ime metal šetnja znak'), c('kost', 'žvakanje zubi igra hrana pas bijelo'), c('kućica', 'dvorište krov spavanje pas drvo zaklon'), c('povodac', 'šetnja ruka ogrlica ulica kontrola pas'), c('njuška', 'miris nos hrana vlažno trag pas')]),
      f('mačka', [c('brkovi', 'lice tanko osjetilo mačka nos dodir'), c('rep', 'ravnoteža pokret dug mačka krzno signal'), c('mjaukanje', 'zvuk glad noć glas mačka pažnja'), c('kandže', 'oštre šapa grebanje lov namještaj zaštita'), c('krzno', 'meko dlaka četka linjanje toplo boja'), c('klupko', 'vuna igra šapa kotrljanje zabava mače'), c('posuda', 'hrana voda kuhinja mačka obrok pod'), c('prozor', 'pogled sunce sjedenje mačka ptica mir')]),
      f('lav', [c('griva', 'dlaka vrat mužjak zlatno snaga kralj'), c('rika', 'zvuk savana opasnost glas strah moć'), c('savana', 'trava sunce Afrika prostor lov vrućina'), c('čopor', 'grupa lavice mladunci lov vođa porodica'), c('kandže', 'oštre šapa lov snaga plijen napad'), c('plijen', 'lov životinja trkа hrana oprez savana'), c('zub', 'oštro vilica meso ugriz snaga bijelo'), c('kralj', 'životinje snaga griva simbol moć ponos')]),
      f('konj', [c('kopito', 'noga potkovica zvuk trkа tvrdo trag'), c('sedlo', 'jahanje koža leđa uzde vozač oprema'), c('griva', 'dlaka vrat vjetar četka ljepota konj'), c('štala', 'slama vrata hrana miris konj farma'), c('uzde', 'kontrola ruke jahanje koža pravac sedlo'), c('galop', 'brzina trkа polje pokret snaga ritam'), c('potkovica', 'metal kopito sreća ekser zaštita kovač'), c('jahač', 'sedlo kaciga ruke trkа konj trening')]),
      f('ptica', [c('krilo', 'let perje nebo mahanje visina ptica'), c('gnijezdo', 'grane jaja mladunci drvo sigurnost proljeće'), c('kljun', 'hrana sjeme zvuk žuto ptica oštro'), c('perje', 'lagano boja krilo rep mekano ptica'), c('pjesma', 'zvuk jutro grana proljeće melodija ptica'), c('jato', 'grupa nebo let pravac ptice pokret'), c('jaje', 'ljuska gnijezdo mladunče bijelo krhko početak'), c('grana', 'drvo sjedenje gnijezdo list visina ptica')]),
      f('riba', [c('peraja', 'plivanje voda ravnoteža pokret tijelo riba'), c('krljušt', 'sjaj tijelo zaštita voda srebrno koža'), c('akvarijum', 'staklo voda biljke hrana riba kuća'), c('udica', 'ribolov mamac štap voda čekanje ribar'), c('mreža', 'hvatanje čamac ribar more riba konopac'), c('škrge', 'disanje voda tijelo riba otvor život'), c('jato', 'grupa plivanje pravac voda sigurnost riba'), c('rep', 'pokret plivanje pravac tijelo peraja brzina')]),
      f('pčela', [c('košnica', 'med vosak matica roj saće rad'), c('med', 'slatko tegla doručak pčela vosak zlatno'), c('ubod', 'bol žaoka oprez koža pčela otok'), c('cvijet', 'polen latica miris proljeće nektar boja'), c('krila', 'zujanje let malo prozirno brzina pčela'), c('matica', 'košnica kraljica jaja roj pčele glavna'), c('saće', 'vosak ćelije med košnica oblik žuto'), c('zujanje', 'zvuk let pčela uho ljeto oprez')]),
      f('zmija', [c('koža', 'ljuske hladno presvlačenje šara tijelo zmija'), c('otrov', 'ugriz opasnost zubi strah lijek zmija'), c('jezik', 'račvast miris pokret usta oprez zmija'), c('puzanje', 'tlo pokret tiho trava tijelo vijuganje'), c('kamen', 'sunce toplota skrivanje priroda sivo zmija'), c('terarijum', 'staklo pijesak grana voda zatvoreno zmija'), c('ugriz', 'zubi bol otrov rana opasnost napad'), c('šara', 'boja tijelo kamuflaža koža priroda oblik')]),
      f('slon', [c('surla', 'nos duga voda hrana snaga slon'), c('kljova', 'bijelo slonovača zub duga odbrana par'), c('uho', 'veliko mahanje toplota glava slon sivo'), c('krdo', 'grupa porodica savana mladunci kretanje zaštita'), c('savana', 'trava Afrika sunce prostor prašina vrućina'), c('težina', 'veliko stopalo zemlja snaga hod trag'), c('voda', 'kupanje surla prskanje rijeka blato hlađenje'), c('čuvar', 'zoološki vrt hrana briga ograda životinja')]),
      f('žirafa', [c('vrat', 'dug visina list drvo glava žirafa'), c('šare', 'mrlje boja koža smeđe tijelo prepoznavanje'), c('list', 'hrana drvo visina zeleno grana ukus'), c('savana', 'Afrika trava sunce prostor životinja vrućina'), c('kopito', 'noga hod trag tvrdo visina zemlja'), c('jezik', 'dug hrana list tamno usta hvatanje'), c('mladunče', 'malo porodica rast zaštita majka visoko'), c('zoološki vrt', 'ograda posjetioci čuvar hrana životinja prostor')]),
    ],
  },
  {
    id: 'umetnost',
    title: 'Umjetnost',
    icon: '🎨',
    colors: ['#db2777', '#be185d'],
    finals: [
      f('slika', [c('platno', 'ram boja atelje površina zid slikar'), c('četkica', 'vlakna potez boja ruka paleta voda'), c('paleta', 'boje drvo krug slikar miješanje nijansa'), c('ram', 'ivica zid drvo galerija slika zaštita'), c('motiv', 'pejzaž portret ideja prizor umjetnik detalj'), c('boja', 'tuba nijansa četka pigment sloj platno'), c('atelje', 'prostor slikar miris platno svjetlo boja'), c('galerija', 'zid posjeta izložba slike tišina opis')]),
      f('muzej', [c('eksponat', 'predmet vitrina opis istorija pažnja zbirka'), c('kustos', 'stručnjak postavka vodič znanje muzej posao'), c('ulaznica', 'karta posjeta cijena šalter papir datum'), c('galerija', 'zid izložba slika prostor publika tišina'), c('vitrina', 'staklo predmet zaštita svjetlo opis zaključano'), c('postavka', 'raspored tema prostor kustos izložba plan'), c('posjetioci', 'grupa tišina pogled karta hodnik pitanja'), c('zbirka', 'predmeti istorija umjetnost čuvanje muzej vrijednost')]),
      f('muzika', [c('nota', 'linije melodija papir znak ritam kompozitor'), c('gitara', 'žice akord solo drvo trzalica bend'), c('ritam', 'bubanj tempo ples otkucaj takt ponavljanje'), c('pjesma', 'tekst refren glas radio melodija stih'), c('mikrofon', 'glas zvuk bina koncert pjevač kabl'), c('klavir', 'tipke crno bijelo melodija prsti sala'), c('koncert', 'publika bina svjetla aplauz karta bend'), c('album', 'pjesme omot izdanje lista slušanje naslov')]),
      f('pozorište', [c('scena', 'daske zavjesa svjetlo gluma publika kulisa'), c('glumac', 'uloga tekst kostim publika pokret glas'), c('predstava', 'čin aplauz režija veče scena drama'), c('karta', 'sjedište red ulaz blagajna cijena datum'), c('zavjesa', 'crveno početak kraj scena tkanina otvaranje'), c('kostim', 'odjeća lik boja šminka nastup garderoba'), c('režiser', 'vizija upute proba scena tekst ekipa'), c('publika', 'aplauz sjedišta tišina reakcija sala gledanje')]),
      f('knjiga', [c('korice', 'naslov slika papir zaštita autor boja'), c('stranica', 'broj tekst list čitanje papir red'), c('pisac', 'autor priča roman pero ideja ime'), c('biblioteka', 'polica tišina članarina pozajmica knjige sto'), c('poglavlje', 'naslov dio radnja stranice nastavak kraj'), c('lik', 'ime priča karakter roman dijalog uloga'), c('roman', 'radnja stranice pisac žanr čitanje korice'), c('bookmark', 'oznaka stranica čitanje papir mjesto nastavak')]),
      f('film', [c('kamera', 'snimanje objektiv kadar set režiser slika'), c('glumac', 'uloga scena dijalog premijera kostim lik'), c('bioskop', 'platno kokice sjedište mrak karta zvuk'), c('režiser', 'akcija vizija ekipa scenario kadar upute'), c('scenario', 'tekst dijalog scena radnja papir autor'), c('montaža', 'rez kadar rezanje ritam zvuk slika'), c('premijera', 'crveni tepih publika prvi prikaz blic'), c('plakat', 'slika naslov glumci najava zid reklama')]),
      f('skulptura', [c('kamen', 'mermer dlijeto težina oblik figura tvrdo'), c('bronza', 'metal liv spomenik sjaj kip boja'), c('figura', 'tijelo forma poza detalj lice umjetnost'), c('postament', 'baza visina muzej natpis kamen oslonac'), c('dlijeto', 'alat udarac kamen ruka oblik prašina'), c('kipar', 'umjetnik forma materijal atelje rad figura'), c('spomenik', 'trg istorija natpis figura bronza sjećanje'), c('muzej', 'postavka eksponat tišina posjeta opis zaštita')]),
      f('ples', [c('korak', 'pokret ritam stopalo vježba takt ples'), c('muzika', 'tempo melodija zvuk ritam pjesma sala'), c('partner', 'par okret držanje scena ruka sklad'), c('kostim', 'haljina boja nastup sjaj pokret scena'), c('bina', 'svjetla publika pod nastup zavjesa aplauz'), c('koreografija', 'redosled pokret plan vježba grupa tačnost'), c('balet', 'špice tutu scena klasika elegancija ravnoteža'), c('aplauz', 'publika kraj uspjeh zvuk dlanovi osmijeh')]),
      f('strip', [c('kadar', 'okvir slika redosled scena crtež priča'), c('oblačić', 'tekst govor misao balon junak dijalog'), c('junak', 'kostim avantura moć priča protivnik hrabrost'), c('crtež', 'linija tuš olovka papir stil boja'), c('tabla', 'stranica kadrovi naslov papir čitanje niz'), c('zlikovac', 'protivnik plan maska opasnost sukob sjena'), c('onomatopeja', 'zvuk slova udarac efekat akcija prasak'), c('scenarista', 'priča tekst ideja dijalog radnja autor')]),
      f('fotografija', [c('aparat', 'sočivo dugme blic snimak fokus ruka'), c('portret', 'lice osoba poza pogled kadar svjetlo'), c('album', 'uspomene stranice slike porodica papir red'), c('fokus', 'oštrina zamućenje objektiv detalj kadar lice'), c('blic', 'svjetlo mrak trenutak aparat sjaj oko'), c('kadar', 'okvir scena kompozicija izbor pogled objektiv'), c('objektiv', 'staklo zum fokus aparat svjetlo krug'), c('uspomena', 'slika događaj porodica putovanje vrijeme osmijeh')]),
    ],
  },
  {
    id: 'prevoz',
    title: 'Prevoz',
    icon: '🚗',
    colors: ['#ca8a04', '#ea580c'],
    finals: [
      f('automobil', [c('volan', 'ruke skretanje točak vozač pravac kontrola'), c('motor', 'snaga gorivo hauba zvuk ulje brzina'), c('guma', 'točak asfalt pritisak šara felna rezerva'), c('semafor', 'crveno zeleno raskrsnica stop žuto signal'), c('sjedalo', 'pojas udobnost vozač putnik naslon kabina'), c('retrovisor', 'ogledalo pogled nazad staklo ugao sigurnost'), c('brzina', 'kazaljka kilometri gas put motor kontrola'), c('parking', 'mjesto rampa karta garaža linije auto')]),
      f('autobus', [c('stanica', 'čekanje tabla linija red putnici klupa'), c('karta', 'cijena vožnja kontrolor validacija papir zona'), c('vozač', 'volan uniforma ruta kočenje ogledalo kabina'), c('putnici', 'sjedišta gužva ulaz izlaz torba razgovor'), c('vrata', 'otvaranje ulaz stepenik dugme zatvaranje stanica'), c('linija', 'broj ruta mapa stanice grad raspored'), c('rukohvat', 'stajanje gužva sigurnost metal autobus ravnoteža'), c('klima', 'vazduh ljeto hladno prozor dugme udobnost')]),
      f('voz', [c('pruga', 'šina kolosjek stanica pravac metal kamen'), c('vagon', 'sjedišta kupe prozor spoj vrata hodnik'), c('lokomotiva', 'vuča mašina snaga početak voz dim'), c('kondukter', 'karta uniforma pregled putnik vagon kliješta'), c('peron', 'stanica čekanje tabla polazak kofer gužva'), c('kupe', 'sjedište vrata prozor prtljag mir putnik'), c('red', 'vrijeme polazak dolazak tabela stanica kašnjenje'), c('tunel', 'mrak pruga zid svjetlo prolaz zvuk')]),
      f('avion', [c('pilot', 'kabina let komande uniforma kapetan slušalice'), c('krilo', 'letelica vazduh motor visina oblaci stabilnost'), c('pista', 'poletanje sletanje aerodrom svjetla beton brzina'), c('prtljag', 'kofer traka težina čekiranje etiketa torba'), c('gejt', 'ukrcavanje tabla broj red pasoš čekanje'), c('sjedište', 'pojas prozor red broj putnik naslon'), c('stjuardesa', 'uniforma piće sigurnost prolaz osmijeh upute'), c('kontrola', 'skener torba dokument red sigurnost policija')]),
      f('bicikl', [c('pedala', 'noge lanac okretanje vožnja ritam pogon'), c('točak', 'guma felna krug osovina brzina put'), c('kaciga', 'glava zaštita traka sigurnost pad vozač'), c('kočnica', 'ručica zaustavljanje pakne brzina sigurnost kontrola'), c('lanac', 'metal zupčanik mast pedala pogon okvir'), c('sjedalo', 'visina udobnost vožnja biciklista položaj okvir'), c('volan', 'ruke skretanje pravac ručke kontrola staza'), c('zvonce', 'signal zvuk upozorenje gužva ručka bicikl')]),
      f('brod', [c('sidro', 'luka lanac dno stajanje metal spuštanje'), c('paluba', 'gore mornari ograda šetnja more kapetan'), c('kapetan', 'komanda uniforma posada kurs kormilo brod'), c('more', 'talasi voda plovidba obala dubina so'), c('kabina', 'krevet prozor brod putnik vrata mala'), c('mornar', 'posada konopac paluba uniforma rad luka'), c('kormilo', 'pravac brod okretanje kapetan kontrola drvo'), c('luka', 'vez obala brod sidro kran pristanište')]),
      f('tramvaj', [c('šina', 'ulica metal pravac stanica točak kolosjek'), c('struja', 'kabl mreža napajanje iskra pantograf vožnja'), c('stanica', 'peron tabla čekanje linija ljudi red'), c('zvono', 'signal upozorenje zvuk vozač skretanje gužva'), c('vagon', 'sjedišta vrata prozor rukohvat putnici pod'), c('karta', 'validacija cijena aparat kontrola papir vožnja'), c('raskrsnica', 'semafor šina ulica auto pješak skretanje'), c('vozač', 'kabina komande uniforma pravac kočenje ogledalo')]),
      f('taksi', [c('taksimetar', 'cijena kilometri ekran vožnja vrijeme iznos'), c('adresa', 'ulica broj odredište navigacija grad mapa'), c('vozač', 'volan ruta razgovor licenca auto sjedište'), c('žuto', 'boja tabla auto grad prepoznatljivo svjetlo'), c('poziv', 'telefon aplikacija narudžba čekanje lokacija broj'), c('račun', 'plaćanje kartica gotovina iznos kraj papir'), c('gepek', 'kofer prtljag vrata prostor torba putnik'), c('navigacija', 'mapa ruta glas skretanje ekran cilj')]),
      f('metro', [c('tunel', 'podzemlje mrak šina zid brzina svjetlo'), c('stanica', 'peron mapa linija izlaz gužva tabla'), c('voz', 'vagoni brzina vrata putnici šina zvuk'), c('karta', 'automat zona ulaz validacija cijena papir'), c('eskalator', 'stepenice pokret gore dolje stanica ljudi'), c('mapa', 'linije boje stanice čvor pravac grad'), c('vrata', 'otvaranje zatvaranje signal putnici peron oprez'), c('gužva', 'ljudi jutro posao čekanje prostor buka')]),
      f('kamion', [c('teret', 'roba kutije težina isporuka paleta skladište'), c('prikolica', 'dužina točkovi spoj transport metal teret'), c('vozač', 'kabina put pauza volan ruta umor'), c('autoput', 'traka brzina naplata znak kilometri vozila'), c('kabina', 'sjedište krevet radio vozač prozor visina'), c('gorivo', 'pumpa rezervoar dizel cijena stanica potrošnja'), c('utovar', 'viljuškar rampa roba skladište paleta radnik'), c('isporuka', 'adresa paket rok potpis kupac kamion')]),
    ],
  },
  {
    id: 'sport',
    title: 'Sport',
    icon: '⚽',
    colors: ['#16a34a', '#0f766e'],
    finals: [
      f('fudbal', [c('gol', 'mreža stativa šut rezultat slavlje lopta'), c('lopta', 'okruglo koža teren dodavanje šut igra'), c('sudija', 'pištaljka karton pravila faul odluka teren'), c('tim', 'igrači dres trener klupa kapiten ekipa'), c('teren', 'trava linije centar gol aut korner'), c('navijači', 'tribina pjesma zastava aplauz stadion buka'), c('kopačke', 'đon pertle trava oprema brzina udarac'), c('liga', 'sezona tabela bodovi klub derbi prvak')]),
      f('košarka', [c('koš', 'obruč mrežica tabla poeni šut skok'), c('dribling', 'lopta pod ruka kontrola brzina prodor'), c('patike', 'parket skok đon pertle oprema korak'), c('trojka', 'linija šut daljina publika pogodak poeni'), c('tabla', 'staklo obruč odskok koš parket sala'), c('playmaker', 'dodavanje taktika lopta napad asistencija tempo'), c('faul', 'kontakt sudija pištaljka slobodna linija kazna'), c('timeout', 'trener klupa savjet pauza taktika minuta')]),
      f('tenis', [c('reket', 'žice drška udarac oprema loptica servis'), c('mreža', 'teren prepreka sredina loptica linija poen'), c('servis', 'početak bacanje as linija brzina reket'), c('gem', 'poeni set meč prednost rezultat tabla'), c('šljaka', 'crveno prašina klizanje teren trag patike'), c('loptica', 'žuto filc odskok reket udarac mreža'), c('sudija', 'stolica odluka aut linija poen meč'), c('publika', 'tišina aplauz tribine meč finale uzdah')]),
      f('plivanje', [c('bazen', 'voda staza hlor pločice dubina skok'), c('naočare', 'oči guma providno zaštita voda lice'), c('kraul', 'stil ruke disanje brzina voda zamah'), c('peškir', 'sušenje svlačionica mokro tkanina bazen torba'), c('kapica', 'glava guma kosa voda takmičenje boja'), c('start', 'blok pištaljka skok početak reakcija trka'), c('delfin', 'stil talas ruke snaga voda ritam'), c('medalja', 'takmičenje postolje pobjeda zlato rezultat plivač')]),
      f('trčanje', [c('staza', 'krug atletika linija tartan trka cilj'), c('patike', 'đon pertle korak udobnost asfalt tempo'), c('maraton', 'dužina izdržljivost cilj kilometri grad umor'), c('štoperica', 'vrijeme sekunde start rezultat trener mjerenje'), c('start', 'pištolj linija reakcija takmičari početak nervoza'), c('cilj', 'traka kraj pobjeda vrijeme aplauz rezultat'), c('tempo', 'ritam disanje korak brzina snaga kontrola'), c('broj', 'majica učesnik trka papir takmičenje identitet')]),
      f('odbojka', [c('mreža', 'visina teren preko blok lopta sredina'), c('servis', 'početak udarac linija lopta as rotacija'), c('smeč', 'skok snaga poen napad ruka blok'), c('ekipa', 'šest rotacija dres klupa trener igrači'), c('blok', 'ruke mreža skok odbrana napad poen'), c('prijem', 'podlaktica servis kontrola lopta odbrana tim'), c('set', 'poeni rezultat kraj pobjeda tabela pauza'), c('libero', 'odbrana dres prijem parket brzina specijalista')]),
      f('bicikl', [c('točak', 'guma felna okretanje krug brzina put'), c('pedala', 'noge lanac pokret vožnja ritam snaga'), c('kaciga', 'glava zaštita sigurnost traka pad vozač'), c('staza', 'put park brzina krivina asfalt priroda'), c('lanac', 'metal zupčanik podmazivanje pedala pogon bicikl'), c('kočnica', 'ručica zaustavljanje brzina sigurnost guma kontrola'), c('sjedalo', 'visina udobnost vožnja okvir položaj biciklista'), c('volan', 'ruke pravac skretanje kontrola ručke put')]),
      f('skijanje', [c('snijeg', 'bijelo hladno pahulja zima staza planina'), c('staza', 'spust žičara planina oznaka brzina krivina'), c('pancerice', 'čizma kopča tvrdo stopalo oprema skija'), c('štapovi', 'ruke oslonac par metal ravnoteža snijeg'), c('skije', 'duge klizanje vosak rubovi oprema spust'), c('žičara', 'sjedište uspon planina red karta visina'), c('kaciga', 'glava zaštita pad sigurnost naočare brzina'), c('instruktor', 'čas početnik savjet tehnika staza oprema')]),
      f('boks', [c('rukavice', 'šake udarac koža zaštita crveno ring'), c('ring', 'konopci ugao borba pod sudija publika'), c('runda', 'vrijeme gong pauza sudija borba minuta'), c('trener', 'savjeti peškir ugao priprema taktika glas'), c('nokaut', 'pad odbrojavanje sudija pobjeda udarac publika'), c('gard', 'ruke zaštita lice stav odbrana borac'), c('pojas', 'šampion titula koža nagrada pobjeda struk'), c('vreća', 'trening udarci težina lanac sala snaga')]),
      f('teretana', [c('tegovi', 'kilogrami ruke snaga metal podizanje serija'), c('traka', 'trčanje brzina ekran korak kardio znoj'), c('proteini', 'ishrana mišići prah oporavak šejk boca'), c('ogledalo', 'odraz forma zid vježba tijelo pogled'), c('klupa', 'ležanje tegovi prsa oslonac sprava sala'), c('sprava', 'metal podešavanje težina vježba sjedište ručke'), c('trener', 'plan savjet tehnika forma motivacija cilj'), c('svlačionica', 'ormarić tuš peškir patike torba odmor')]),
    ],
  },
  {
    id: 'tehnologija',
    title: 'Tehnologija',
    icon: '💻',
    colors: ['#7c3aed', '#4f46e5'],
    finals: [
      f('kompjuter', [c('monitor', 'ekran slika piksel sto svjetlo rezolucija'), c('tastatura', 'slova tipke unos prečica pisanje kabl'), c('miš', 'klik kursor točkić podloga ruka dugme'), c('procesor', 'čip brzina jezgro računanje toplota hardver'), c('memorija', 'ram podaci brzina modul kapacitet program'), c('kućište', 'ventilator kabl metal dugme napajanje prašina'), c('program', 'ikonica prozor meni funkcija instalacija rad'), c('fajl', 'folder naziv ekstenzija dokument kopija save')]),
      f('telefon', [c('ekran', 'dodir staklo osvjetljenje aplikacija slika zaštita'), c('baterija', 'punjenje procenat kabl struja trajanje ikona'), c('kamera', 'slika sočivo video selfi blic fokus'), c('poruka', 'tekst chat obavještenje kontakt telefon zvuk'), c('sim', 'kartica broj mreža operater poziv signal'), c('futrola', 'zaštita maska guma boja pad ivica'), c('punjač', 'kabl utičnica struja baterija brzina adapter'), c('aplikacija', 'ikonica meni dugme notifikacija instalacija nalog')]),
      f('internet', [c('ruter', 'signal wifi lampica mreža kabl lozinka'), c('browser', 'tab adresa stranica pretraga link prozor'), c('link', 'klik url plavo veza stranica dijeljenje'), c('server', 'hosting podaci zahtjev odgovor mreža cloud'), c('wifi', 'signal lozinka ruter brzina telefon mreža'), c('pretraga', 'riječ rezultat stranica browser pitanje klik'), c('email', 'poruka sanduče adresa prilog slanje inbox'), c('download', 'fajl brzina internet folder traka završetak')]),
      f('aplikacija', [c('ikonica', 'slika meni telefon klik ekran prečica'), c('dugme', 'akcija pritisak tekst boja dodir ekran'), c('notifikacija', 'zvuk poruka baner alarm obavještenje telefon'), c('profil', 'slika ime nalog podešavanja korisnik avatar'), c('login', 'email lozinka prijava nalog sesija sigurnost'), c('update', 'verzija promjena download instalacija store napredak'), c('meni', 'opcije lista dugme navigacija ekran izbor'), c('forma', 'unos polje tekst potvrda greška dugme')]),
      f('programiranje', [c('kod', 'linije sintaksa fajl editor funkcija logika'), c('funkcija', 'poziv parametar povratak logika kod ime'), c('bug', 'greška test popravka problem crash poruka'), c('git', 'commit branch repo verzija push pull'), c('terminal', 'komanda tekst putanja proces izlaz ekran'), c('editor', 'fajl linije tema kursor prečica kod'), c('algoritam', 'koraci logika rješenje petlja uslov ulaz'), c('debug', 'breakpoint greška konzola test trag vrijednost')]),
      f('robot', [c('senzor', 'detekcija svjetlo pokret ulaz signal mjerenje'), c('motor', 'okretanje snaga točak struja brzina osovina'), c('metal', 'tijelo šraf ram čvrsto konstrukcija ploča'), c('automatika', 'zadaci kontrola proces mašina program sistem'), c('kamera', 'vid slika prepoznavanje objektiv robot senzor'), c('baterija', 'napajanje punjenje energija kabl trajanje ćelija'), c('ruka', 'hvatanje zglob pokret alat prsti servo'), c('program', 'naredba algoritam kontrola kod logika izvršenje')]),
      f('kamera', [c('sočivo', 'staklo fokus zum svjetlo objektiv oštrina'), c('fotografija', 'slika album uspomena klik kadar boja'), c('blic', 'svjetlo mrak trenutak osvjetljenje dugme bljesak'), c('video', 'snimak pokret zvuk film kadar kamera'), c('fokus', 'oštrina objektiv detalj lice zum dubina'), c('memorija', 'kartica fajl prostor snimak čuvanje kapacitet'), c('statív', 'noge stabilno visina kamera snimanje ugao'), c('kadar', 'okvir scena kompozicija slika pogled izbor')]),
      f('igrica', [c('kontroler', 'dugmad džojstik ruke konzola vibracija igra'), c('misija', 'zadatak prepreka poeni napredak cilj mapa'), c('grafika', 'slika boje ekran animacija detalj svijet'), c('rezultat', 'poeni rekord tabla pobjednik kraj nivo'), c('nivo', 'težina napredak mapa neprijatelj cilj prolaz'), c('avatar', 'lik izgled igrač kostim ime profil'), c('zvuk', 'muzika efekat pucanj korak atmosfera slušalice'), c('online', 'igrači mreža tim chat server meč')]),
      f('lozinka', [c('nalog', 'korisnik email profil prijava aplikacija sigurnost'), c('sigurnost', 'zaštita ključ tajna rizik provjera kod'), c('šifra', 'brojevi slova znakovi unos tajna polje'), c('login', 'prijava forma dugme sesija email lozinka'), c('token', 'kod pristup potvrda aplikacija server vrijeme'), c('haker', 'napad krađa rizik mreža podaci oprez'), c('dvokorak', 'telefon kod potvrda sigurnost poruka prijava'), c('reset', 'email link promjena zaborav potvrda nalog')]),
      f('cloud', [c('fajl', 'upload download folder backup dokument prostor'), c('nalog', 'lozinka email login profil pristup korisnik'), c('server', 'podaci mreža centar hosting zahtjev odgovor'), c('sinhronizacija', 'uređaji kopija ažuriranje veza vrijeme automatski'), c('backup', 'kopija čuvanje povratak sigurnost folder server'), c('prostor', 'gigabajt kapacitet nalog fajl limit plaćanje'), c('dijeljenje', 'link pristup folder tim dozvola email'), c('aplikacija', 'telefon računar nalog upload download ikonica')]),
    ],
  },
  {
    id: 'hrana',
    title: 'Hrana',
    icon: '🍕',
    colors: ['#f97316', '#dc2626'],
    finals: [
      f('ručak', [
        c('tanjir', 'porcija sto jelo keramika pribor ivica'),
        c('supa', 'kašika lonac povrće para toplo bujon'),
        c('meso', 'tiganj roštilj protein nož porcija pečenje'),
        c('salata', 'krastavac paradajz ulje činija svježe zeleno'),
        c('hleb', 'korica brašno pekara kriška miris pecivo'),
        c('pribor', 'viljuška nož kašika salveta sto metal'),
        c('kuvar', 'recept kecelja kuhinja nož začin lonac'),
        c('sto', 'stolnjak tanjir čaša porodica stolica ručak'),
      ]),
      f('pizza', [
        c('sir', 'topljenje kačkavalj mlijeko rendanje žuto ukus'),
        c('testo', 'brašno kvasac voda miješenje kora rerna'),
        c('paradajz', 'sos crveno pelat povrće kriška slatko'),
        c('peć', 'toplota rerna kora pečenje drva temperatura'),
        c('origano', 'začin miris trava teglica italija zeleno'),
        c('šunka', 'meso kriška sendvič ružičasto topping slano'),
        c('kutija', 'karton dostava poklopac vruće kuća porudžbina'),
        c('porudžbina', 'telefon dostava adresa meni cijena čekanje'),
      ]),
      f('kafa', [
        c('šolja', 'drška toplo napitak keramika tanjirić gutljaj'),
        c('zrno', 'mljevenje miris prženje arabika braon mlin'),
        c('mlijeko', 'pjena bijelo kapućino krava čaša dodatak'),
        c('jutro', 'buđenje doručak alarm dan rutina posao'),
        c('šećer', 'slatko kocka kašičica kristal bijelo tegla'),
        c('aparat', 'dugme para kapsula voda šolja kuhinja'),
        c('miris', 'aroma kuhinja jutro toplo zrno ukus'),
        c('kafić', 'sto konobar račun društvo šolja terasa'),
      ]),
      f('hleb', [
        c('brašno', 'pšenica bijelo testo mlinar prah kesa'),
        c('kvasac', 'dizanje mehurići fermentacija toplota tijesto miris'),
        c('korica', 'hrskavo pečenje braon ivica miris kora'),
        c('pekara', 'miris jutro pecivo prodavnica toplo red'),
        c('kriška', 'nož tanjir namaz doručak sendvič komad'),
        c('rernа', 'toplota pečenje pleh kuhinja temperatura vrata'),
        c('sendvič', 'sir šunka salata hleb užina papir'),
        c('mrvica', 'sto pod hleb sitno čišćenje korica'),
      ]),
      f('salata', [
        c('krastavac', 'zeleno svježe kolut voda kora povrće'),
        c('paradajz', 'crveno sočno sjemenke sos povrće kriška'),
        c('ulje', 'maslina preliv flaša kap sjaj ukus'),
        c('činija', 'miješanje sto posuda serviranje velika staklo'),
        c('so', 'slano kristal začin prstohvat bijelo teglica'),
        c('sirće', 'kiselo flaša preliv salata miris kap'),
        c('zelena', 'list hrskavo svježe voda bašta salata'),
        c('nož', 'sječenje oštrica daska povrće kuhinja metal'),
      ]),
      f('čokolada', [
        c('kakao', 'zrno braon gorko biljka prah tropi'),
        c('šećer', 'slatko kristal bijelo kašičica kocka tegla'),
        c('tabla', 'kockica folija lomljenje red omot komad'),
        c('desert', 'poslastica kolač uživanje slatkiš tanjir krema'),
        c('mlijeko', 'bijelo krava napitak dodatak čaša kremasto'),
        c('lješnik', 'orašasto tvrdo ukus punjenje kolač krckanje'),
        c('omot', 'papir boja marka otvaranje folija reklama'),
        c('kolač', 'rernа tijesto krema rođendan tanjir slatko'),
      ]),
      f('supa', [
        c('kašika', 'jelo metal duboko pribor tanjir gutljaj'),
        c('šargarepa', 'narandžasto povrće sjeckanje korijen supa zdravo'),
        c('lonac', 'kuvanje poklopac para ringla voda metal'),
        c('bujon', 'tečnost ukus kocka toplo supa slano'),
        c('rezanci', 'tanko tijesto supa kašika mekano žuto'),
        c('peršun', 'zeleno list miris začin tanjir svježe'),
        c('piletina', 'meso bijelo kost supa kuvanje komad'),
        c('para', 'toplota lonac poklopac kuhinja magla miris'),
      ]),
      f('sladoled', [
        c('kornet', 'hrskavo vafl drška kugla ljeto jestivo'),
        c('vanila', 'bijelo miris ukus štapić krema slatko'),
        c('zamrzivač', 'hladno led fioka čuvanje kuhinja vrata'),
        c('ljeto', 'vrućina sunce raspust osvježenje plaža dan'),
        c('kugla', 'okruglo kašika kornet ukus porcija slatko'),
        c('čokolada', 'braon kakao preliv slatko ukus komadić'),
        c('jagoda', 'crveno voće sirup ukus svježe ljeto'),
        c('štapić', 'drvo držanje lizanje sladoled ruka kraj'),
      ]),
      f('restoran', [
        c('meni', 'jelo cijena izbor konobar stranica ponuda'),
        c('konobar', 'uniforma narudžba sto račun tacna gost'),
        c('račun', 'cijena plaćanje papir novac kusur kraj'),
        c('sto', 'rezervacija stolica tanjir čaša salveta gost'),
        c('kuvar', 'kuhinja recept lonac začin jelo vruće'),
        c('gosti', 'razgovor večera stolice društvo narudžba atmosfera'),
        c('porudžbina', 'meni konobar čekanje jelo kuhinja zapis'),
        c('salveta', 'papir sto ruke čisto tanjir preklop'),
      ]),
      f('kuhinja', [
        c('šporet', 'ringla ručak toplota lonac plin dugme'),
        c('frižider', 'hladno namirnice vrata polica mlijeko led'),
        c('nož', 'sječenje oštrica daska povrće kuvar metal'),
        c('recept', 'uputstvo sastojci koraci ukus mjera vrijeme'),
        c('sudopera', 'voda slavina suđe pranje sapun odvod'),
        c('daska', 'sječenje drvo povrće nož kuhinja površina'),
        c('lonac', 'poklopac para kuvanje supa metal ringla'),
        c('začin', 'miris teglica so biber ukus polica'),
      ]),
    ],
  },
];

export const LETTERS = ['A', 'B', 'C', 'D'];
