import { StyleSheet } from 'react-native';

export function createStyles(theme) {
  return StyleSheet.create({
    background: {
      flex: 1,
    },
    safeArea: {
      flex: 1,
    },
    homeContent: {
      flex: 1,
      justifyContent: 'center',
      padding: 16,
    },
    logoCircle: {
      alignItems: 'center',
      alignSelf: 'center',
      backgroundColor: theme.accent,
      borderColor: theme.border,
      borderRadius: 28,
      borderWidth: 1,
      height: 88,
      justifyContent: 'center',
      marginBottom: 18,
      width: 88,
    },
    logoIcon: {
      fontSize: 46,
    },
    logoTitle: {
      color: theme.text,
      fontSize: 30,
      fontWeight: '900',
      textAlign: 'center',
    },
    logoSubtitle: {
      color: theme.mutedText,
      fontSize: 16,
      marginBottom: 14,
      marginTop: 6,
      textAlign: 'center',
    },
    homeLevelBadge: {
      alignItems: 'center',
      alignSelf: 'center',
      backgroundColor: theme.panel,
      borderColor: theme.border,
      borderRadius: 8,
      borderWidth: 1,
      flexDirection: 'row',
      gap: 10,
      marginBottom: 24,
      paddingHorizontal: 14,
      paddingVertical: 10,
    },
    homeLevelIcon: {
      fontSize: 20,
    },
    homeLevelCopy: {
      gap: 2,
    },
    homeLevelLabel: {
      color: theme.mutedText,
      fontSize: 10,
      fontWeight: '900',
      textTransform: 'uppercase',
    },
    homeLevelValue: {
      color: theme.text,
      fontSize: 14,
      fontWeight: '900',
    },
    menuStack: {
      gap: 11,
    },
    menuButton: {
      alignItems: 'center',
      borderColor: theme.border,
      borderRadius: 8,
      borderWidth: 1,
      flexDirection: 'row',
      gap: 16,
      minHeight: 60,
      paddingHorizontal: 16,
    },
    menuIconBox: {
      alignItems: 'center',
      backgroundColor: 'rgba(255, 255, 255, 0.22)',
      borderRadius: 8,
      height: 40,
      justifyContent: 'center',
      width: 40,
    },
    menuIcon: {
      color: '#ffffff',
      fontSize: 20,
      fontWeight: '900',
    },
    menuButtonText: {
      color: '#ffffff',
      fontSize: 16,
      fontWeight: '900',
    },
    versionText: {
      color: theme.mutedText,
      fontSize: 12,
      marginTop: 28,
      textAlign: 'center',
    },
    pressed: {
      opacity: 0.86,
      transform: [{ scale: 0.99 }],
    },
    headerBar: {
      alignItems: 'center',
      backgroundColor: theme.panel,
      borderColor: theme.border,
      borderRadius: 8,
      borderWidth: 1,
      flexDirection: 'row',
      justifyContent: 'space-between',
      margin: 10,
      minHeight: 54,
      paddingHorizontal: 14,
    },
    headerLeft: {
      alignItems: 'center',
      flexDirection: 'row',
      gap: 10,
    },
    headerIconButton: {
      alignItems: 'center',
      height: 34,
      justifyContent: 'center',
      width: 34,
    },
    headerIconText: {
      color: theme.text,
      fontSize: 28,
      fontWeight: '700',
    },
    headerTitle: {
      color: theme.text,
      fontSize: 20,
      fontWeight: '900',
    },
    levelList: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 10,
      justifyContent: 'space-between',
      padding: 10,
      paddingBottom: 28,
    },
    levelCard: {
      alignItems: 'center',
      borderColor: theme.border,
      borderRadius: 8,
      borderWidth: 1,
      minHeight: 156,
      overflow: 'hidden',
      padding: 16,
      width: '48.5%',
    },
    levelCardWide: {
      width: '100%',
    },
    levelIcon: {
      fontSize: 34,
    },
    levelTitle: {
      color: '#ffffff',
      fontSize: 19,
      fontWeight: '900',
      marginTop: 8,
      textAlign: 'center',
    },
    levelSubtitle: {
      color: '#ffffff',
      fontSize: 16,
      fontWeight: '800',
      marginTop: 8,
    },
    playButton: {
      alignItems: 'center',
      backgroundColor: 'rgba(255, 255, 255, 0.18)',
      borderColor: 'rgba(255, 255, 255, 0.22)',
      borderRadius: 8,
      borderWidth: 1,
      height: 34,
      justifyContent: 'center',
      marginTop: 'auto',
      width: '100%',
    },
    playButtonText: {
      color: '#ffffff',
      fontSize: 15,
      fontWeight: '900',
    },
    statsList: {
      gap: 12,
      padding: 10,
      paddingBottom: 28,
    },
    metricGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 10,
      justifyContent: 'space-between',
    },
    metricCard: {
      borderColor: theme.border,
      borderRadius: 8,
      borderWidth: 1,
      minHeight: 126,
      padding: 16,
      width: '48.5%',
    },
    metricIconBox: {
      alignItems: 'center',
      backgroundColor: 'rgba(255, 255, 255, 0.15)',
      borderRadius: 8,
      height: 44,
      justifyContent: 'center',
      width: 44,
    },
    metricIcon: {
      color: '#ffffff',
      fontSize: 22,
    },
    metricLabel: {
      color: '#ffffff',
      fontSize: 12,
      fontWeight: '800',
      lineHeight: 16,
      marginTop: 14,
    },
    metricValue: {
      color: '#ffffff',
      fontSize: 28,
      fontWeight: '900',
      marginTop: 4,
    },
    metricDescription: {
      color: 'rgba(255, 255, 255, 0.84)',
      fontSize: 12,
      fontWeight: '700',
      lineHeight: 16,
      marginTop: 8,
    },
    howContent: {
      gap: 14,
      padding: 10,
      paddingBottom: 28,
    },
    sectionTitle: {
      color: theme.text,
      fontSize: 18,
      fontWeight: '900',
      marginLeft: 2,
      marginTop: 4,
    },
    ruleCard: {
      borderRadius: 10,
      flexDirection: 'row',
      gap: 14,
      padding: 18,
    },
    ruleIconBox: {
      alignItems: 'center',
      backgroundColor: 'rgba(255, 255, 255, 0.18)',
      borderRadius: 8,
      height: 48,
      justifyContent: 'center',
      width: 48,
    },
    ruleIcon: {
      color: '#ffffff',
      fontSize: 24,
      fontWeight: '900',
    },
    ruleCopy: {
      flex: 1,
    },
    ruleStep: {
      color: '#d9edff',
      fontSize: 12,
      fontWeight: '700',
    },
    ruleTitle: {
      color: '#ffffff',
      fontSize: 18,
      fontWeight: '900',
      marginTop: 4,
    },
    ruleText: {
      color: '#ffffff',
      fontSize: 14,
      lineHeight: 20,
      marginTop: 10,
    },
    infoPanel: {
      backgroundColor: theme.panel,
      borderColor: theme.border,
      borderRadius: 8,
      borderWidth: 1,
      gap: 10,
      padding: 18,
    },
    infoTitle: {
      color: theme.text,
      fontSize: 17,
      fontWeight: '900',
      marginBottom: 4,
    },
    infoText: {
      color: theme.text,
      fontSize: 13,
      fontWeight: '700',
      lineHeight: 20,
    },
    settingsList: {
      gap: 12,
      padding: 8,
      paddingBottom: 30,
    },
    settingsPanel: {
      backgroundColor: theme.panel,
      borderColor: theme.border,
      borderRadius: 8,
      borderWidth: 1,
      gap: 12,
      padding: 18,
    },
    settingRow: {
      alignItems: 'center',
      flexDirection: 'row',
      gap: 14,
    },
    settingIconBox: {
      alignItems: 'center',
      backgroundColor: theme.primarySoft,
      borderRadius: 8,
      height: 46,
      justifyContent: 'center',
      width: 46,
    },
    settingIcon: {
      color: theme.text,
      fontSize: 20,
      fontWeight: '900',
    },
    settingCopy: {
      flex: 1,
    },
    settingTitle: {
      color: theme.text,
      fontSize: 16,
      fontWeight: '900',
    },
    settingHint: {
      color: theme.mutedText,
      fontSize: 13,
      lineHeight: 18,
      marginTop: 5,
    },
    panelTitle: {
      color: theme.text,
      fontSize: 17,
      fontWeight: '900',
      marginBottom: 6,
    },
    difficultyRow: {
      flexDirection: 'row',
      gap: 8,
    },
    difficultyOption: {
      alignItems: 'center',
      backgroundColor: theme.primarySoft,
      borderColor: theme.border,
      borderRadius: 8,
      borderWidth: 1,
      flex: 1,
      minHeight: 62,
      justifyContent: 'center',
    },
    difficultyOptionActive: {
      backgroundColor: theme.success,
      borderColor: theme.success,
    },
    difficultyNumber: {
      color: theme.text,
      fontSize: 18,
      fontWeight: '900',
    },
    difficultyLabel: {
      color: theme.mutedText,
      fontSize: 12,
      fontWeight: '800',
      marginTop: 3,
    },
    difficultyTextActive: {
      color: theme.mode === 'dark' ? '#073b1b' : '#ffffff',
    },
    difficultySummary: {
      backgroundColor: theme.primarySoft,
      borderRadius: 8,
      gap: 6,
      padding: 12,
    },
    themeGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
      justifyContent: 'space-between',
    },
    themeOption: {
      backgroundColor: theme.primarySoft,
      borderColor: theme.border,
      borderRadius: 8,
      borderWidth: 1,
      minHeight: 54,
      padding: 10,
      width: '48.5%',
    },
    themeOptionActive: {
      backgroundColor: theme.accentSoft,
      borderColor: theme.accent,
    },
    themeSwatches: {
      flexDirection: 'row',
      gap: 5,
      marginBottom: 8,
    },
    themeSwatch: {
      borderRadius: 10,
      height: 14,
      width: 14,
    },
    themeOptionText: {
      color: theme.text,
      fontSize: 13,
      fontWeight: '900',
    },
    infoRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
    },
    infoRowLabel: {
      color: theme.mutedText,
      fontSize: 14,
      fontWeight: '700',
    },
    infoRowValue: {
      color: theme.text,
      fontSize: 14,
      fontWeight: '900',
    },
    dangerPanel: {
      backgroundColor: theme.dangerSoft,
      borderColor: theme.danger,
    },
    trashBox: {
      alignItems: 'center',
      backgroundColor: theme.dangerSoft,
      borderRadius: 8,
      height: 46,
      justifyContent: 'center',
      width: 46,
    },
    resetButton: {
      alignItems: 'center',
      alignSelf: 'center',
      backgroundColor: theme.danger,
      borderRadius: 8,
      height: 46,
      justifyContent: 'center',
      marginTop: 4,
      width: '82%',
    },
    resetButtonText: {
      color: '#ffffff',
      fontSize: 14,
      fontWeight: '900',
    },
    gameShell: {
      flex: 1,
    },
    gameContent: {
      gap: 10,
      padding: 10,
      paddingBottom: 160,
    },
    loadingBox: {
      alignItems: 'center',
      flex: 1,
      gap: 14,
      justifyContent: 'center',
    },
    loadingText: {
      color: theme.text,
      fontSize: 16,
      fontWeight: '800',
    },
    scorePanel: {
      backgroundColor: theme.panel,
      borderColor: theme.border,
      borderRadius: 8,
      borderWidth: 1,
      padding: 10,
    },
    scoreGrid: {
      flexDirection: 'row',
      gap: 8,
    },
    scoreBox: {
      borderColor: theme.border,
      borderRadius: 7,
      borderWidth: 1,
      flex: 1,
      minHeight: 58,
      padding: 10,
    },
    scoreLabel: {
      color: '#ffffff',
      fontSize: 11,
      fontWeight: '700',
    },
    scoreValue: {
      color: theme.scoreValue,
      fontSize: 20,
      fontWeight: '900',
      marginTop: 5,
    },
    progressTrack: {
      flexDirection: 'row',
      gap: 5,
      marginTop: 10,
    },
    progressSegment: {
      backgroundColor: theme.primarySoft,
      borderRadius: 10,
      flex: 1,
      height: 6,
    },
    progressSegmentActive: {
      backgroundColor: theme.accent,
    },
    sourceText: {
      color: theme.mutedText,
      fontSize: 11,
      fontWeight: '700',
      textAlign: 'right',
    },
    sourceRow: {
      alignItems: 'center',
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginTop: 8,
    },
    surrenderButton: {
      alignItems: 'center',
      backgroundColor: theme.dangerSoft,
      borderColor: theme.danger,
      borderRadius: 999,
      borderWidth: 1,
      minHeight: 28,
      justifyContent: 'center',
      paddingHorizontal: 10,
    },
    surrenderButtonText: {
      color: theme.text,
      fontSize: 11,
      fontWeight: '900',
    },
    columnsGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'space-between',
      rowGap: 10,
    },
    columnCard: {
      backgroundColor: theme.panel,
      borderColor: theme.border,
      borderRadius: 8,
      borderWidth: 1,
      padding: 10,
      width: '48%',
    },
    blitzCard: {
      backgroundColor: theme.panel,
      borderColor: theme.border,
      borderRadius: 8,
      borderWidth: 1,
      padding: 12,
      width: '100%',
    },
    columnCardSolved: {
      borderColor: theme.success,
    },
    columnHeader: {
      alignItems: 'center',
      flexDirection: 'row',
      justifyContent: 'space-between',
    },
    columnBadge: {
      alignItems: 'center',
      backgroundColor: theme.primarySoft,
      borderColor: theme.border,
      borderRadius: 7,
      borderWidth: 1,
      height: 32,
      justifyContent: 'center',
      width: 32,
    },
    columnLetter: {
      color: theme.text,
      fontSize: 16,
      fontWeight: '900',
    },
    columnPoints: {
      alignItems: 'center',
      backgroundColor: theme.accentSoft,
      borderColor: theme.accent,
      borderRadius: 8,
      borderWidth: 1,
      justifyContent: 'center',
      minHeight: 30,
      minWidth: 48,
      paddingHorizontal: 8,
      paddingVertical: 4,
    },
    columnPointsDisabled: {
      opacity: 0.42,
    },
    columnPointsText: {
      color: theme.text,
      fontSize: 11,
      fontWeight: '900',
    },
    blitzHeaderActions: {
      alignItems: 'center',
      flexDirection: 'row',
      gap: 8,
    },
    blitzSkipButton: {
      alignItems: 'center',
      backgroundColor: theme.accentSoft,
      borderColor: theme.accent,
      borderRadius: 8,
      borderWidth: 1,
      justifyContent: 'center',
      minHeight: 30,
      paddingHorizontal: 10,
      paddingVertical: 4,
    },
    blitzSkipButtonText: {
      color: theme.accent,
      fontSize: 11,
      fontWeight: '900',
    },
    columnProgressTrack: {
      flexDirection: 'row',
      gap: 4,
      marginBottom: 8,
      marginTop: 8,
    },
    columnProgressSegment: {
      backgroundColor: theme.primarySoft,
      borderRadius: 10,
      flex: 1,
      height: 4,
    },
    columnProgressSegmentActive: {
      backgroundColor: theme.success,
    },
    clueCell: {
      alignItems: 'center',
      backgroundColor: theme.hiddenCell,
      borderColor: theme.border,
      borderRadius: 6,
      borderWidth: 1,
      minHeight: 42,
      justifyContent: 'center',
      marginBottom: 7,
      paddingHorizontal: 6,
      paddingVertical: 5,
    },
    clueCellOpen: {
      backgroundColor: theme.openCell,
      borderColor: theme.openCellBorder,
    },
    clueText: {
      color: '#ffffff',
      fontSize: 13,
      fontWeight: '900',
      includeFontPadding: true,
      lineHeight: 18,
      textAlign: 'center',
    },
    clueTextHidden: {
      color: theme.softText,
      fontSize: 15,
      lineHeight: 20,
    },
    columnInput: {
      backgroundColor: theme.input,
      borderColor: theme.border,
      borderRadius: 7,
      borderWidth: 1,
      color: theme.inputText,
      fontSize: 12,
      height: 34,
      paddingHorizontal: 10,
      paddingVertical: 0,
      textAlignVertical: 'center',
    },
    columnInputSolved: {
      backgroundColor: theme.inputSolved,
      color: theme.inputSolvedText,
      fontWeight: '900',
    },
    columnMetaRow: {
      alignItems: 'center',
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: 7,
      marginTop: 2,
    },
    possiblePoints: {
      color: theme.mutedText,
      fontSize: 12,
      fontWeight: '700',
    },
    possiblePointsValue: {
      color: theme.success,
      fontWeight: '900',
    },
    attemptText: {
      color: theme.mutedText,
      fontSize: 11,
      fontWeight: '700',
    },
    okButton: {
      alignItems: 'center',
      backgroundColor: theme.primary,
      borderRadius: 7,
      height: 34,
      justifyContent: 'center',
      marginTop: 7,
    },
    okButtonText: {
      color: '#ffffff',
      fontSize: 12,
      fontWeight: '900',
    },
    blitzFeedbackBox: {
      backgroundColor: theme.successSoft,
      borderColor: theme.success,
      borderRadius: 7,
      borderWidth: 1,
      marginBottom: 8,
      paddingHorizontal: 10,
      paddingVertical: 8,
    },
    blitzSkippedBox: {
      backgroundColor: theme.accentSoft,
      borderColor: theme.accent,
    },
    blitzWrongBox: {
      backgroundColor: theme.dangerSoft,
      borderColor: theme.danger,
    },
    blitzFeedbackTitle: {
      color: theme.success,
      fontSize: 13,
      fontWeight: '900',
      textAlign: 'center',
    },
    blitzSkippedTitle: {
      color: theme.accent,
    },
    blitzWrongTitle: {
      color: theme.danger,
    },
    blitzFeedbackAnswer: {
      color: theme.text,
      fontSize: 14,
      fontWeight: '900',
      marginTop: 2,
      textAlign: 'center',
    },
    blitzResultStats: {
      gap: 6,
      marginTop: 12,
    },
    blitzMissedList: {
      gap: 10,
      marginTop: 12,
    },
    blitzMissedItem: {
      borderColor: theme.border,
      borderTopWidth: 1,
      paddingTop: 10,
    },
    blitzMissedAnswer: {
      color: theme.text,
      fontSize: 15,
      fontWeight: '900',
    },
    blitzMissedMeta: {
      color: theme.mutedText,
      fontSize: 12,
      fontWeight: '700',
      marginTop: 3,
    },
    finalPanel: {
      backgroundColor: theme.panelStrong,
      borderColor: theme.accent,
      borderRadius: 8,
      borderWidth: 1,
      padding: 16,
    },
    finalTitle: {
      color: theme.text,
      fontSize: 18,
      fontWeight: '900',
      textAlign: 'center',
    },
    finalHint: {
      color: theme.mutedText,
      fontSize: 14,
      fontWeight: '700',
      marginTop: 8,
      textAlign: 'center',
    },
    finalInput: {
      backgroundColor: theme.input,
      borderColor: theme.border,
      borderRadius: 8,
      borderWidth: 1,
      color: theme.inputText,
      fontSize: 14,
      height: 42,
      marginTop: 14,
      paddingHorizontal: 12,
      paddingVertical: 0,
      textAlignVertical: 'center',
    },
    finalMetaRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginTop: 8,
    },
    finalMetaText: {
      color: theme.accent,
      fontSize: 12,
      fontWeight: '800',
    },
    finalButton: {
      alignItems: 'center',
      backgroundColor: theme.accent,
      borderRadius: 8,
      height: 42,
      justifyContent: 'center',
      marginTop: 10,
    },
    finalButtonText: {
      color: theme.accentText,
      fontSize: 14,
      fontWeight: '900',
    },
    homeButton: {
      alignItems: 'center',
      backgroundColor: theme.primary,
      borderRadius: 8,
      height: 44,
      justifyContent: 'center',
      marginTop: 10,
    },
    homeButtonText: {
      color: '#ffffff',
      fontSize: 14,
      fontWeight: '900',
    },
    disabledButton: {
      opacity: 0.48,
    },
  });
}
